/** Shared visual tokens — Sprint 35 doctor experience polish (75–80% viewport target). */
export const ECG_WORKSTATION_VISUAL = {
  leftCollapsedWidth: 26,
  leftExpandedWidth: 114,
  leftPanelMaxWidth: 200,
  leftPanelMinWidth: 96,
  miniNavigatorHeight: 32,
  monitorBorderRadius: 2,
  panelAutoHideDelayMs: 2400,
  panelBorderRadius: 2,
  rightCollapsedWidth: 26,
  rightExpandedWidth: 171,
  rightPanelMaxWidth: 240,
  rightPanelMinWidth: 140,
  statusBarHeight: 22,
  statusBarMinHeight: 22,
  statusBarUpdateIntervalMs: 500,
  toolbarButtonSize: 20,
  toolbarMaxHeight: 16,
  toolbarGroupGap: 1,
  floatingToolSize: 22,
  transitionMs: 150,
  viewportTargetMin: 0.75,
  viewportTargetMax: 0.8,
  workspaceGap: 0,
  workspacePadding: 0,
  toolbarButtonHeight: 20,
  toolbarButtonMinWidth: 20,
} as const;
