/** Shared visual tokens — Sprint 33.5 pixel-perfect polish. */
export const ECG_WORKSTATION_VISUAL = {
  leftCollapsedWidth: 28,
  leftExpandedWidth: 152,
  leftPanelMaxWidth: 248,
  leftPanelMinWidth: 128,
  miniNavigatorHeight: 36,
  monitorBorderRadius: 3,
  panelAutoHideDelayMs: 2400,
  panelBorderRadius: 3,
  rightCollapsedWidth: 28,
  rightExpandedWidth: 228,
  rightPanelMaxWidth: 300,
  rightPanelMinWidth: 180,
  statusBarHeight: 24,
  statusBarMinHeight: 24,
  statusBarUpdateIntervalMs: 500,
  toolbarButtonSize: 22,
  toolbarMaxHeight: 18,
  toolbarGroupGap: 2,
  floatingToolSize: 24,
  transitionMs: 150,
  workspaceGap: 0,
  workspacePadding: 0,
  toolbarButtonHeight: 22,
  toolbarButtonMinWidth: 22,
} as const;
