import type { NotificationRuleDefinition } from "./types";

export const DEFAULT_NOTIFICATION_RULES: NotificationRuleDefinition[] = [
  {
    category: "CRITICAL_ECG_ALERT",
    deliveryModes: ["IN_APP", "EMAIL_READY", "PUSH_READY"],
    description: "Critical ECG findings require immediate clinician attention.",
    eventType: "CRITICAL_ECG",
    name: "Critical ECG Alert",
    notificationType: "CRITICAL",
    priority: "CRITICAL",
    ruleCode: "critical_ecg_alert",
    templateKey: "critical_ecg_alert",
  },
  {
    category: "HIGH_RISK_ECG",
    deliveryModes: ["IN_APP", "EMAIL_READY"],
    description: "High-risk ECG findings require prompt review.",
    eventType: "HIGH_RISK_ECG",
    name: "High Risk ECG",
    notificationType: "WARNING",
    priority: "HIGH",
    ruleCode: "high_risk_ecg",
    templateKey: "high_risk_ecg",
  },
  {
    category: "PHYSICIAN_REVIEW_REQUIRED",
    deliveryModes: ["IN_APP", "EMAIL_READY"],
    description: "Case requires physician review.",
    eventType: "PHYSICIAN_REVIEW_REQUIRED",
    name: "Physician Review Required",
    notificationType: "WARNING",
    priority: "HIGH",
    ruleCode: "physician_review_required",
    templateKey: "physician_review_required",
  },
  {
    category: "FOLLOW_UP_DUE",
    deliveryModes: ["IN_APP", "EMAIL_READY"],
    description: "Follow-up ECG is due.",
    eventType: "FOLLOW_UP_DUE",
    name: "Follow-up Due",
    notificationType: "INFO",
    priority: "MEDIUM",
    ruleCode: "follow_up_due",
    templateKey: "follow_up_due",
  },
  {
    category: "FOLLOW_UP_OVERDUE",
    deliveryModes: ["IN_APP", "EMAIL_READY", "PUSH_READY"],
    description: "Follow-up ECG is overdue.",
    eventType: "FOLLOW_UP_OVERDUE",
    name: "Follow-up Overdue",
    notificationType: "WARNING",
    priority: "HIGH",
    ruleCode: "follow_up_overdue",
    templateKey: "follow_up_overdue",
  },
  {
    category: "AI_ANALYSIS_COMPLETED",
    deliveryModes: ["IN_APP"],
    description: "AI analysis completed for case.",
    eventType: "AI_ANALYSIS_COMPLETED",
    name: "AI Analysis Completed",
    notificationType: "SUCCESS",
    priority: "MEDIUM",
    ruleCode: "ai_analysis_completed",
    templateKey: "ai_analysis_completed",
  },
  {
    category: "REPORT_GENERATION",
    deliveryModes: ["IN_APP", "EMAIL_READY"],
    description: "Clinical report approved.",
    eventType: "REPORT_APPROVED",
    name: "Report Approved",
    notificationType: "SUCCESS",
    priority: "MEDIUM",
    ruleCode: "report_approved",
    templateKey: "report_approved",
  },
  {
    category: "REPORT_GENERATION",
    deliveryModes: ["IN_APP", "EMAIL_READY"],
    description: "Clinical report rejected.",
    eventType: "REPORT_REJECTED",
    name: "Report Rejected",
    notificationType: "WARNING",
    priority: "HIGH",
    ruleCode: "report_rejected",
    templateKey: "report_rejected",
  },
  {
    category: "REPORT_GENERATION",
    deliveryModes: ["IN_APP", "WEBHOOK_READY"],
    description: "Clinical report exported.",
    eventType: "REPORT_EXPORTED",
    name: "Report Exported",
    notificationType: "INFO",
    priority: "LOW",
    ruleCode: "report_exported",
    templateKey: "report_exported",
  },
  {
    category: "CASE_ARCHIVED",
    deliveryModes: ["IN_APP"],
    description: "Case archived.",
    eventType: "CASE_ARCHIVED",
    name: "Case Archived",
    notificationType: "INFO",
    priority: "LOW",
    ruleCode: "case_archived",
    templateKey: "case_archived",
  },
  {
    category: "CASE_RESTORED",
    deliveryModes: ["IN_APP"],
    description: "Case restored from archive.",
    eventType: "CASE_RESTORED",
    name: "Case Restored",
    notificationType: "INFO",
    priority: "LOW",
    ruleCode: "case_restored",
    templateKey: "case_restored",
  },
  {
    category: "TIMELINE_UPDATED",
    deliveryModes: ["IN_APP"],
    description: "Patient or case timeline updated.",
    eventType: "TIMELINE_UPDATED",
    name: "Timeline Updated",
    notificationType: "INFO",
    priority: "LOW",
    ruleCode: "timeline_updated",
    templateKey: "timeline_updated",
  },
];
