import type { GuidelineReference, KnowledgeBaseEntry, MedicalDiagnosisCode } from "../types";

const AHA_ECG: GuidelineReference = {
  organization: "AHA/ACCF/HRS",
  title: "Recommendations for the Standardization and Interpretation of the Electrocardiogram",
  year: 2009,
};

const ESC_ACS: GuidelineReference = {
  organization: "ESC",
  title: "Guidelines for the management of acute coronary syndromes",
  year: 2023,
};

const AHA_AF: GuidelineReference = {
  organization: "AHA/ACC/HRS",
  title: "Guidelines for the Management of Patients With Atrial Fibrillation",
  year: 2023,
};

const ESC_SYNC: GuidelineReference = {
  organization: "ESC",
  title: "Guidelines for the management of syncope",
  year: 2018,
};

function entry(
  code: MedicalDiagnosisCode,
  label: string,
  category: KnowledgeBaseEntry["category"],
  severity: KnowledgeBaseEntry["severity"],
  urgency: KnowledgeBaseEntry["urgency"],
  fields: Omit<KnowledgeBaseEntry, "code" | "label" | "category" | "severity" | "urgency">,
): KnowledgeBaseEntry {
  return { code, label, category, severity, urgency, ...fields };
}

export const KNOWLEDGE_BASE: KnowledgeBaseEntry[] = [
  entry("NSR", "Normal Sinus Rhythm", "rhythm", "normal", "routine", {
    diagnosticCriteria: [
      "Regular rhythm with P wave before each QRS",
      "Heart rate 60–100 bpm in adults",
      "Normal PR interval (120–200 ms)",
      "Normal QRS duration (<120 ms)",
    ],
    ecgCharacteristics: ["Upright P in I, II, aVF", "Constant PR interval", "Normal axis (−30° to +90°)"],
    measurements: ["Heart rate", "PR interval", "QRS duration", "QT/QTc", "Axis"],
    differentialDiagnosis: ["Sinus arrhythmia", "Ectopic atrial rhythm", "Junctional rhythm with retrograde P"],
    pitfalls: ["Athletic bradycardia may appear normal at rest", "Lead misplacement mimics axis change", "Artifact may simulate irregularity"],
    clinicalNotes: ["Baseline for comparison with future tracings", "Does not exclude structural heart disease"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("SBRAD", "Sinus Bradycardia", "rhythm", "minor", "routine", {
    diagnosticCriteria: ["Regular rhythm", "Heart rate <60 bpm", "P before each QRS", "Normal PR and QRS"],
    ecgCharacteristics: ["Normal sinus P morphology", "Gradual rate change with respiration possible"],
    measurements: ["Heart rate", "PR interval", "QTc"],
    differentialDiagnosis: ["Junctional rhythm", "Second-degree AV block", "Medication effect (beta-blocker)"],
    pitfalls: ["Athletes may have physiologic bradycardia", "Hypothermia and hypothyroidism cause bradycardia"],
    clinicalNotes: ["Symptomatic bradycardia warrants evaluation", "Consider Holter if syncope present"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("STACH", "Sinus Tachycardia", "rhythm", "minor", "routine", {
    diagnosticCriteria: ["Regular rhythm", "Heart rate >100 bpm", "P before each QRS"],
    ecgCharacteristics: ["Rate-dependent PR shortening", "Normal QRS morphology"],
    measurements: ["Heart rate", "PR interval", "ST-T changes at high rate"],
    differentialDiagnosis: ["SVT", "Atrial flutter with 2:1 block", "Anxiety/hyperthyroidism"],
    pitfalls: ["P waves may merge with T waves at high rates", "Always seek underlying cause"],
    clinicalNotes: ["Treat underlying cause (fever, pain, hypovolemia, PE, anemia)"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("AF", "Atrial Fibrillation", "rhythm", "abnormal", "urgent", {
    diagnosticCriteria: ["Irregularly irregular rhythm", "Absent distinct P waves", "Variable RR intervals"],
    ecgCharacteristics: ["Fibrillatory baseline", "Irregular ventricular response", "Narrow or wide QRS"],
    measurements: ["Heart rate", "RR variability", "QRS duration"],
    differentialDiagnosis: ["Atrial flutter with variable block", "Multifocal atrial tachycardia", "Frequent PACs"],
    pitfalls: ["Coarse AF may resemble flutter", "Artifact can mimic irregularity", "WPW with AF is dangerous"],
    clinicalNotes: ["Assess stroke risk (CHA₂DS₂-VASc)", "Rate vs rhythm control strategy", "Anticoagulation per guidelines"],
    guidelineReferences: [AHA_AF, AHA_ECG],
  }),
  entry("AFL", "Atrial Flutter", "rhythm", "abnormal", "urgent", {
    diagnosticCriteria: ["Regular or irregular atrial activity ~250–350/min", "Sawtooth flutter waves best in II, III, aVF", "Often fixed AV conduction (2:1, 3:1, 4:1)"],
    ecgCharacteristics: ["Negative sawtooth in inferior leads", "Regular ventricular response if fixed block"],
    measurements: ["Atrial rate estimate", "Ventricular rate", "QRS duration"],
    differentialDiagnosis: ["SVT", "Atrial tachycardia", "Coarse atrial fibrillation"],
    pitfalls: ["2:1 block may hide flutter waves", "Variable block mimics AF"],
    clinicalNotes: ["Similar stroke risk to AF", "Ablation highly effective for typical flutter"],
    guidelineReferences: [AHA_AF],
  }),
  entry("PAC", "Premature Atrial Contraction", "rhythm", "minor", "routine", {
    diagnosticCriteria: ["Early P wave with abnormal morphology", "Narrow QRS (unless aberrancy)", "Non-compensatory pause"],
    ecgCharacteristics: ["Premature P", "May have aberrant conduction (Ashman)"],
    measurements: ["Coupling interval", "QRS duration"],
    differentialDiagnosis: ["PVC with retrograde P", "Junctional premature beat", "Artifact"],
    pitfalls: ["Aberrant PAC may mimic PVC", "Frequent PACs may trigger AF"],
    clinicalNotes: ["Usually benign; evaluate if frequent or symptomatic"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("PVC", "Premature Ventricular Contraction", "rhythm", "minor", "routine", {
    diagnosticCriteria: ["Early wide QRS without preceding P", "Compensatory pause", "Discordant ST-T"],
    ecgCharacteristics: ["Wide QRS >120 ms", "Bizarre morphology", "Full compensatory pause"],
    measurements: ["QRS duration", "Coupling interval", "PVC burden if Holter"],
    differentialDiagnosis: ["Aberrant PAC", "Pre-excited beat", "Artifact"],
    pitfalls: ["Multifocal PVCs suggest cardiomyopathy", "R-on-T in Long QT is dangerous"],
    clinicalNotes: ["Frequent PVCs (>10%) may cause cardiomyopathy", "Evaluate structural heart disease if symptomatic"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("SVT", "Supraventricular Tachycardia", "rhythm", "urgent", "urgent", {
    diagnosticCriteria: ["Regular narrow-complex tachycardia", "Rate typically 150–250 bpm", "Abrupt onset/offset"],
    ecgCharacteristics: ["P waves may be hidden in QRS/ST", "Narrow QRS unless BBB"],
    measurements: ["Heart rate", "QRS duration", "RP/PR relationship if P visible"],
    differentialDiagnosis: ["Sinus tachycardia", "Atrial flutter", "Atrial tachycardia", "Junctional tachycardia"],
    pitfalls: ["Antidromic AVRT has wide QRS", "Irregular SVT may be AF or MAT"],
    clinicalNotes: ["Vagal maneuvers, adenosine for diagnosis/termination", "Avoid AV nodal blockers in WPW"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("VT", "Ventricular Tachycardia", "rhythm", "critical", "critical", {
    diagnosticCriteria: ["Wide QRS tachycardia >100 bpm", "AV dissociation (when present)", "Fusion/capture beats"],
    ecgCharacteristics: ["Monomorphic or polymorphic", "Concordance in precordial leads", "Northwest axis"],
    measurements: ["Heart rate", "QRS duration", "QT/QTc baseline"],
    differentialDiagnosis: ["SVT with aberrancy", "Antidromic WPW", "Pacemaker-mediated tachycardia"],
    pitfalls: ["Always treat wide-complex tachycardia as VT until proven otherwise", "Adenosine contraindicated"],
    clinicalNotes: ["Hemodynamically unstable → immediate cardioversion", "Amiodarone/lidocaine per ACLS"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("VF", "Ventricular Fibrillation", "rhythm", "critical", "critical", {
    diagnosticCriteria: ["Chaotic irregular waveform", "No identifiable QRS", "Rate indeterminate"],
    ecgCharacteristics: ["Coarse or fine fibrillation", "No organized rhythm"],
    measurements: ["None reliable during VF"],
    differentialDiagnosis: ["Artifact", "Asystole with fine baseline", "Torsades de pointes degenerating to VF"],
    pitfalls: ["Fine VF may resemble asystole", "Confirm on multiple leads"],
    clinicalNotes: ["Immediate defibrillation per ACLS", "Treat reversible causes (5 Hs and 5 Ts)"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("ASYSTOLE", "Asystole", "rhythm", "critical", "critical", {
    diagnosticCriteria: ["Flat line or minimal electrical activity", "No QRS complexes", "Confirm in multiple leads"],
    ecgCharacteristics: ["Isoelectric baseline", "May have P waves only (PEA variant)"],
    measurements: ["None"],
    differentialDiagnosis: ["Fine VF", "Lead disconnect", "Low gain setting"],
    pitfalls: ["Always confirm cable connection and gain", "Check multiple leads"],
    clinicalNotes: ["CPR and epinephrine per ACLS", "Not shockable rhythm"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("PEA", "Pulseless Electrical Activity", "rhythm", "critical", "critical", {
    diagnosticCriteria: ["Organized electrical activity on ECG", "No palpable pulse", "Any rhythm except VF/pVT"],
    ecgCharacteristics: ["May show bradyarrhythmia, idioventricular rhythm, or narrow complex"],
    measurements: ["Heart rate if organized", "QRS width"],
    differentialDiagnosis: ["True asystole", "Severe hypotension with palpable pulse missed"],
    pitfalls: ["Treat underlying cause urgently", "Do not defibrillate PEA"],
    clinicalNotes: ["Search reversible causes: tamponade, tension pneumothorax, massive PE, hypovolemia"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("LBBB", "Left Bundle Branch Block", "conduction", "abnormal", "routine", {
    diagnosticCriteria: ["QRS ≥120 ms", "Broad notched R in I, aVL, V5–V6", "rS or QS in V1"],
    ecgCharacteristics: ["Dominant S in V1", "M-shaped R in lateral leads", "Discordant ST-T"],
    measurements: ["QRS duration", "Axis", "Sgarbossa criteria if ACS suspected"],
    differentialDiagnosis: ["Ventricular rhythm", "Hyperkalemia wide QRS", "Paced rhythm"],
    pitfalls: ["LBBB masks STEMI — use modified Sgarbossa", "New LBBB with ischemia is concerning"],
    clinicalNotes: ["Evaluate for structural heart disease", "Echo recommended for new LBBB"],
    guidelineReferences: [AHA_ECG, ESC_ACS],
  }),
  entry("RBBB", "Right Bundle Branch Block", "conduction", "abnormal", "routine", {
    diagnosticCriteria: ["QRS ≥120 ms", "rsR' (M-shaped) in V1", "Wide S in I, V5–V6"],
    ecgCharacteristics: ["Terminal R in V1", "T wave inversion V1–V3 may be normal"],
    measurements: ["QRS duration", "Axis"],
    differentialDiagnosis: ["RVH", "Brugada pattern", "Posterior MI"],
    pitfalls: ["Incomplete RBBB (100–120 ms) may be normal variant", "New RBBB with PE consider"],
    clinicalNotes: ["May be chronic or acute", "Evaluate RV strain if acute symptoms"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("BIFASC", "Bifascicular Block", "conduction", "abnormal", "urgent", {
    diagnosticCriteria: ["RBBB + LAFB or RBBB + LPFB", "Two of three fascicles blocked"],
    ecgCharacteristics: ["Wide QRS with axis deviation", "Combination of RBBB and hemi-block pattern"],
    measurements: ["QRS duration", "Axis", "PR interval"],
    differentialDiagnosis: ["Trifascicular block", "IVCD", "Ventricular rhythm"],
    pitfalls: ["Progression to complete heart block possible", "Syncope warrants pacemaker evaluation"],
    clinicalNotes: ["High-grade AV block risk", "Electrophysiology referral if symptomatic"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("TRIFASC", "Trifascicular Block", "conduction", "urgent", "urgent", {
    diagnosticCriteria: ["Bifascicular block + first-degree AV block", "Alternating BBB"],
    ecgCharacteristics: ["Variable QRS morphology", "Prolonged PR with bifascicular pattern"],
    measurements: ["PR interval", "QRS duration", "Axis"],
    differentialDiagnosis: ["Complete heart block", "Second-degree AV block Type II"],
    pitfalls: ["High risk of progression to complete AV block", "Temporary pacing may be needed"],
    clinicalNotes: ["Permanent pacemaker often indicated if symptomatic"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("AVB1", "First Degree AV Block", "conduction", "minor", "routine", {
    diagnosticCriteria: ["PR interval >200 ms", "Every P conducts to QRS"],
    ecgCharacteristics: ["Constant prolonged PR", "Normal QRS unless coexisting BBB"],
    measurements: ["PR interval"],
    differentialDiagnosis: ["Enhanced AV nodal conduction with long PR", "Medication effect"],
    pitfalls: ["May progress in Lyme carditis or degenerative disease"],
    clinicalNotes: ["Usually benign in isolation", "Monitor if medication-related"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("AVB2I", "Second Degree AV Block Type I (Wenckebach)", "conduction", "abnormal", "urgent", {
    diagnosticCriteria: ["Progressive PR prolongation until dropped beat", "Grouped beating", "Usually narrow QRS"],
    ecgCharacteristics: ["Cyclic PR lengthening", "Dropped QRS after longest PR"],
    measurements: ["PR interval pattern", "Conduction ratio"],
    differentialDiagnosis: ["Non-conducted PAC", "Second-degree Type II", "High-grade AV block"],
    pitfalls: ["Type I usually AV nodal — often benign", "Inferior MI may cause Type I"],
    clinicalNotes: ["Atropine effective if symptomatic", "Usually does not require pacing"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("AVB2II", "Second Degree AV Block Type II", "conduction", "urgent", "urgent", {
    diagnosticCriteria: ["Fixed PR with sudden dropped QRS", "Often wide QRS (infranodal)", "Mobitz II pattern"],
    ecgCharacteristics: ["Constant PR in conducted beats", "Intermittent non-conducted P waves"],
    measurements: ["PR interval", "QRS duration", "Conduction ratio"],
    differentialDiagnosis: ["Type I block", "Complete heart block", "Non-conducted PAC"],
    pitfalls: ["High risk of progression to complete block", "Requires pacemaker"],
    clinicalNotes: ["Permanent pacemaker indicated", "Avoid AV nodal blocking agents"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("AVB3", "Third Degree (Complete) AV Block", "conduction", "critical", "critical", {
    diagnosticCriteria: ["Complete AV dissociation", "Atrial and ventricular rates independent", "More P waves than QRS"],
    ecgCharacteristics: ["Variable PR", "Escape rhythm (junctional or ventricular)"],
    measurements: ["Atrial rate", "Ventricular rate", "QRS width of escape"],
    differentialDiagnosis: ["AV dissociation with acceleration", "Interference dissociation"],
    pitfalls: ["Ventricular escape <40 bpm is unstable", "Stokes-Adams attacks risk"],
    clinicalNotes: ["Immediate pacing if symptomatic", "Permanent pacemaker required"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("WPW", "Wolff-Parkinson-White Syndrome", "conduction", "abnormal", "urgent", {
    diagnosticCriteria: ["Short PR (<120 ms)", "Delta wave (slurred QRS upstroke)", "Wide QRS"],
    ecgCharacteristics: ["Pre-excitation pattern", "Pseudo-infarction Q waves possible"],
    measurements: ["PR interval", "QRS duration", "Delta wave presence"],
    differentialDiagnosis: ["LBBB", "Hyperkalemia", "Ventricular rhythm"],
    pitfalls: ["AF with WPW → rapid ventricular response → VF risk", "Never give AV nodal blockers in pre-excited AF"],
    clinicalNotes: ["Electrophysiology referral for risk stratification", "Ablation curative in most cases"],
    guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  entry("BRUGADA", "Brugada Syndrome", "channelopathy", "urgent", "urgent", {
    diagnosticCriteria: ["Type 1: coved ST elevation ≥2 mm in ≥1 of V1–V3 followed by negative T", "Spontaneous or drug-induced (ajmaline/flecainide)"],
    ecgCharacteristics: ["RBBB pattern with ST elevation V1–V3", "Saddle-back or coved morphology"],
    measurements: ["ST elevation amplitude", "QRS duration"],
    differentialDiagnosis: ["RBBB", "Early repolarization", "Acute MI anterior", "ARVC"],
    pitfalls: ["Pattern may be intermittent", "Fever unmasks Brugada pattern"],
    clinicalNotes: ["High risk of sudden cardiac death", "ICD if high-risk features or prior cardiac arrest"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("LONG_QT", "Long QT Syndrome", "channelopathy", "urgent", "urgent", {
    diagnosticCriteria: ["QTc >470 ms (male) or >480 ms (female)", "Prolonged repolarization"],
    ecgCharacteristics: ["Prolonged QT interval", "T wave abnormalities", "Torsades de pointes risk"],
    measurements: ["QT interval", "QTc (Bazett, Fridericia)"],
    differentialDiagnosis: ["Hypocalcemia", "Drug effect", "Hypothermia", "Bradycardia-related QT prolongation"],
    pitfalls: ["Correct QT for heart rate", "Many drugs prolong QT"],
    clinicalNotes: ["Review QT-prolonging medications", "Correct electrolytes (K+, Mg2+)"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("SHORT_QT", "Short QT Syndrome", "channelopathy", "abnormal", "urgent", {
    diagnosticCriteria: ["QTc ≤340 ms", "Tall peaked T waves", "Short ST segment"],
    ecgCharacteristics: ["Abbreviated repolarization", "Atrial fibrillation association"],
    measurements: ["QTc"],
    differentialDiagnosis: ["Hypercalcemia", "Normal variant", "Early repolarization"],
    pitfalls: ["Rare but associated with sudden death", "May be missed without measurement"],
    clinicalNotes: ["Family history and genetic testing", "ICD in high-risk patients"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("HYPERK", "Hyperkalemia", "electrolyte", "urgent", "urgent", {
    diagnosticCriteria: ["Peaked T waves", "PR prolongation", "QRS widening", "Sine wave pattern in severe cases"],
    ecgCharacteristics: ["Tent-shaped T waves", "P wave flattening/absence", "Progressive QRS widening"],
    measurements: ["T wave amplitude", "QRS duration", "PR interval"],
    differentialDiagnosis: ["Early repolarization", "Hyperacute T waves in STEMI", "Normal variant peaked T"],
    pitfalls: ["ECG changes correlate poorly with K+ level", "Treat empirically if suspected clinically"],
    clinicalNotes: ["Emergent treatment if ECG changes present", "Calcium gluconate for membrane stabilization"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("HYPOK", "Hypokalemia", "electrolyte", "abnormal", "urgent", {
    diagnosticCriteria: ["T wave flattening/inversion", "Prominent U waves", "ST depression", "QT prolongation"],
    ecgCharacteristics: ["U wave best in V2–V3", "T-U fusion"],
    measurements: ["T wave morphology", "QU interval", "QTc"],
    differentialDiagnosis: ["Digoxin effect", "Long QT", "Normal variant U waves"],
    pitfalls: ["U waves may be subtle", "Arrhythmia risk increases with severity"],
    clinicalNotes: ["Replace potassium cautiously", "Monitor for arrhythmias during repletion"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("HYPOCAL", "Hypocalcemia", "electrolyte", "abnormal", "routine", {
    diagnosticCriteria: ["Prolonged QT interval", "Normal T wave morphology typically"],
    ecgCharacteristics: ["QT prolongation without T wave changes"],
    measurements: ["QT", "QTc"],
    differentialDiagnosis: ["Long QT syndrome", "Hypokalemia", "Drug effect"],
    pitfalls: ["QT prolongation increases torsades risk"],
    clinicalNotes: ["Correct calcium and magnesium", "Evaluate for underlying cause"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("LVH", "Left Ventricular Hypertrophy", "hypertrophy", "abnormal", "routine", {
    diagnosticCriteria: ["Sokolow-Lyon: S in V1 + R in V5/V6 ≥35 mm", "Cornell: R in aVL + S in V3 >28 mm (men) or >20 mm (women)", "Strain pattern supports diagnosis"],
    ecgCharacteristics: ["Increased QRS voltage", "Left axis deviation", "ST-T strain in lateral leads"],
    measurements: ["Sokolow-Lyon index", "Cornell criteria", "QRS duration"],
    differentialDiagnosis: ["Athletic heart", "Anterior MI", "LBBB", "WPW"],
    pitfalls: ["Sensitivity limited; normal ECG does not exclude LVH", "Echo is gold standard"],
    clinicalNotes: ["Associated with hypertension and cardiomyopathy", "Aggressive BP control"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("RVH", "Right Ventricular Hypertrophy", "hypertrophy", "abnormal", "urgent", {
    diagnosticCriteria: ["Right axis deviation", "R > S in V1", "P pulmonale", "Supporting criteria in multiple leads"],
    ecgCharacteristics: ["Dominant R in V1", "T inversion V1–V3", "RAD >+110°"],
    measurements: ["Axis", "R/S ratio V1", "P wave amplitude II"],
    differentialDiagnosis: ["Posterior MI", "RBBB", "WPW", "Dextrocardia"],
    pitfalls: ["Chronic lung disease common cause", "Acute RVH suggests PE or MI"],
    clinicalNotes: ["Evaluate for pulmonary hypertension", "Echo for RV function"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("PERICARDITIS", "Pericarditis", "other", "abnormal", "urgent", {
    diagnosticCriteria: ["Diffuse concave ST elevation", "PR depression", "Spodick sign (downsloping TP)", "No reciprocal ST depression (except aVR/V1)"],
    ecgCharacteristics: ["Four stages of ECG evolution", "No Q waves", "No loss of R waves"],
    measurements: ["ST elevation distribution", "PR segment deviation"],
    differentialDiagnosis: ["Early repolarization", "STEMI", "Myocarditis", "Benign early repolarization"],
    pitfalls: ["Localized pericarditis may mimic STEMI", "Always correlate with troponin and clinical picture"],
    clinicalNotes: ["NSAIDs and colchicine first-line", "Exclude tamponade clinically"],
    guidelineReferences: [ESC_ACS, AHA_ECG],
  }),
  entry("PE", "Pulmonary Embolism", "other", "urgent", "emergent", {
    diagnosticCriteria: ["S1Q3T3 pattern (classic but insensitive)", "Right heart strain: RAD, RBBB, T inversions V1–V4", "Sinus tachycardia most common finding"],
    ecgCharacteristics: ["Tachycardia", "New RBBB", "P pulmonale", "Af in large PE"],
    measurements: ["Heart rate", "Axis", "QRS morphology"],
    differentialDiagnosis: ["ACS", "Pneumothorax", "Anxiety/tachycardia"],
    pitfalls: ["Normal ECG does not exclude PE", "ECG is nonspecific"],
    clinicalNotes: ["Clinical pretest probability + D-dimer/CTPA", "Anticoagulation if confirmed"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("STEMI", "ST-Elevation Myocardial Infarction", "ischemia", "critical", "critical", {
    diagnosticCriteria: ["ST elevation ≥1 mm in ≥2 contiguous leads (≥2 mm in V2–V3 men <40)", "New LBBB with ischemic symptoms counts as STEMI equivalent"],
    ecgCharacteristics: ["Hyperacute T waves early", "ST elevation → Q waves evolve", "Reciprocal ST depression"],
    measurements: ["ST elevation amplitude", "Territory involved", "Time from symptom onset"],
    differentialDiagnosis: ["Pericarditis", "Early repolarization", "LVH strain", "Brugada", "Pacemaker"],
    pitfalls: ["Posterior STEMI: ST depression V1–V3 with tall R", "Right ventricular MI: ST elevation V1 + inferior leads"],
    clinicalNotes: ["Activate cath lab per door-to-balloon targets", "Dual antiplatelet + anticoagulation"],
    guidelineReferences: [ESC_ACS, AHA_ECG],
  }),
  entry("NSTEMI", "Non-ST-Elevation Myocardial Infarction", "ischemia", "urgent", "urgent", {
    diagnosticCriteria: ["ST depression and/or T inversion", "Elevated troponin without ST elevation meeting STEMI criteria"],
    ecgCharacteristics: ["ST depression ≥0.5 mm", "T wave inversion", "Transient ST elevation possible"],
    measurements: ["ST deviation", "T wave changes", "Troponin trend"],
    differentialDiagnosis: ["Stable angina", "Demand ischemia", "Pulmonary embolism", "Pericarditis"],
    pitfalls: ["Dynamic changes warrant serial ECGs", "Wellens syndrome: biphasic T V2–V3 (LAD stenosis)"],
    clinicalNotes: ["Risk stratify with GRACE/TIMI", "Early invasive strategy for high-risk features"],
    guidelineReferences: [ESC_ACS, AHA_ECG],
  }),
  entry("EARLY_REPOL", "Early Repolarization", "other", "normal", "routine", {
    diagnosticCriteria: ["J-point elevation ≥1 mm in ≥2 leads", "Concave ST elevation", "Notable in young males", "Stable pattern"],
    ecgCharacteristics: ["Slurring or notching at J point", "Prominent T waves", "No reciprocal changes"],
    measurements: ["J-point elevation", "ST morphology"],
    differentialDiagnosis: ["Pericarditis", "STEMI", "Brugada type 2"],
    pitfalls: ["May mimic STEMI in young patient", "Compare with prior ECGs"],
    clinicalNotes: ["Benign in most cases", "Inferior early repolarization linked to VF in rare cases"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("HYPERTROPHY", "Hypertrophy (Unspecified)", "hypertrophy", "abnormal", "routine", {
    diagnosticCriteria: ["Increased QRS voltage meeting LVH or RVH criteria", "Atrial enlargement patterns"],
    ecgCharacteristics: ["Voltage criteria met", "Strain patterns", "Atrial abnormalities"],
    measurements: ["Voltage indices", "P wave duration/amplitude"],
    differentialDiagnosis: ["Athletic heart", "Chamber enlargement vs conduction disease"],
    pitfalls: ["ECG has low sensitivity for hypertrophy"],
    clinicalNotes: ["Confirm with echocardiography"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("ELECTROLYTE", "Electrolyte Disorder (Pattern)", "electrolyte", "abnormal", "urgent", {
    diagnosticCriteria: ["ECG pattern consistent with electrolyte disturbance", "Requires laboratory confirmation"],
    ecgCharacteristics: ["Variable depending on specific electrolyte abnormality"],
    measurements: ["QT/QTc", "T wave morphology", "QRS width", "PR interval"],
    differentialDiagnosis: ["Drug effects", "Ischemia", "Channelopathy"],
    pitfalls: ["ECG alone is insufficient for diagnosis"],
    clinicalNotes: ["Obtain electrolyte panel urgently", "Treat based on labs and clinical status"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("DRUG_EFFECT", "Drug Effect on ECG", "other", "minor", "routine", {
    diagnosticCriteria: ["ECG changes temporally related to medication", "Known pharmacologic effect"],
    ecgCharacteristics: ["Digoxin: ST scooping, QT shortening", "TCA: QRS widening, QT prolongation", "Beta-blocker: bradycardia"],
    measurements: ["QTc", "QRS duration", "Heart rate"],
    differentialDiagnosis: ["Primary cardiac disease", "Electrolyte abnormality"],
    pitfalls: ["Multiple drugs may have additive effects"],
    clinicalNotes: ["Review medication list", "Consider drug level if toxicity suspected"],
    guidelineReferences: [AHA_ECG],
  }),
  entry("PACEMAKER", "Pacemaker Rhythm", "other", "minor", "routine", {
    diagnosticCriteria: ["Pacing spikes before P or QRS", "Capture with appropriate morphology", "Failure to capture/sense if malfunction"],
    ecgCharacteristics: ["Spike artifact", "Wide QRS if ventricular pacing", "Fusion beats possible"],
    measurements: ["Pacing rate", "Capture assessment", "Underlying native rhythm"],
    differentialDiagnosis: ["Artifact", "Pre-excitation"],
    pitfalls: ["Oversensing may cause pauses", "Undersensing may cause competition"],
    clinicalNotes: ["Evaluate pacemaker function with device interrogation", "Magnet application per protocol"],
    guidelineReferences: [AHA_ECG],
  }),
];
