ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LICENSE_REVOKED';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lifetimeRevokedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lifetimeRevokedBy" TEXT;

ALTER TABLE "License" ADD COLUMN IF NOT EXISTS "revokedById" TEXT;
ALTER TABLE "License" ADD COLUMN IF NOT EXISTS "revokedAt" TIMESTAMP(3);

ALTER TABLE "License" ADD CONSTRAINT "License_revokedById_fkey" FOREIGN KEY ("revokedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
