import type { EmkpDiseaseEntry, EmkpGuidelineReference, EmkpKnowledgeCategory } from "../model/knowledge-model";

const AHA_ECG: EmkpGuidelineReference = {
  organization: "AHA", documentId: "AHA-ECG-2009", title: "AHA/ACCF/HRS Recommendations for Standardization and Interpretation of the Electrocardiogram", year: 2009,
};
const ESC_ACS: EmkpGuidelineReference = {
  organization: "ESC", documentId: "ESC-ACS-2023", title: "ESC Guidelines for Management of Acute Coronary Syndromes", year: 2023,
};
const ACC_AHA_AF: EmkpGuidelineReference = {
  organization: "ACC/AHA", documentId: "ACC-AHA-AF-2023", title: "ACC/AHA/HRS Guideline for Atrial Fibrillation", year: 2023,
};
const UDMI: EmkpGuidelineReference = {
  organization: "UDMI", documentId: "UDMI-4TH-2018", title: "Fourth Universal Definition of Myocardial Infarction", year: 2018,
};
const ESC_SYNC: EmkpGuidelineReference = {
  organization: "ESC", documentId: "ESC-SYNC-2018", title: "ESC Guidelines for Syncope", year: 2018,
};
const IEC: EmkpGuidelineReference = {
  organization: "IEC", documentId: "IEC-60601-2-25", title: "IEC 60601-2-25 Medical Electrical Equipment — ECG", year: 2011,
};

function disease(
  code: string,
  name: string,
  category: EmkpKnowledgeCategory,
  fields: Omit<EmkpDiseaseEntry, "code" | "name" | "category">,
): EmkpDiseaseEntry {
  return { code, name, category, ...fields };
}

const defaults = {
  evidenceLevel: "B" as const,
  confidence: "high" as const,
  recommendationLevel: "routine" as const,
};

export const EMKP_DISEASES: EmkpDiseaseEntry[] = [
  disease("NORMAL_ECG", "Normal ECG", "normal", {
    ...defaults, definition: "ECG without significant abnormality in rate, rhythm, intervals, axis, or morphology.",
    diagnosticCriteria: ["Heart rate 60–100 bpm", "Regular rhythm", "Normal PR, QRS, QT", "Normal axis", "No significant ST-T changes"],
    ecgCharacteristics: ["Normal sinus P waves", "Narrow QRS", "Normal repolarization"],
    measurements: ["HR", "PR", "QRS", "QTc", "Axis"], differentialDiagnosis: ["Athletic heart", "Early repolarization variant"],
    pitfalls: ["Technical artifact may mimic pathology"], severity: "normal", urgency: "routine", riskCategory: "benign",
    clinicalNotes: ["Baseline for comparison"], guidelineReferences: [AHA_ECG, IEC],
  }),
  disease("NSR", "Sinus Rhythm", "rhythm", {
    ...defaults, definition: "Impulse origin from SA node with P before each QRS.",
    diagnosticCriteria: ["P before every QRS", "Constant PR", "Rate appropriate for context"],
    ecgCharacteristics: ["Upright P in I, II, aVF"], measurements: ["HR", "PR", "RR"],
    differentialDiagnosis: ["Ectopic atrial rhythm", "Junctional rhythm"], pitfalls: ["Sinus arrhythmia is variant of NSR"],
    severity: "normal", urgency: "routine", riskCategory: "benign", clinicalNotes: ["Normal cardiac pacemaker function"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("SBRAD", "Sinus Bradycardia", "rhythm", {
    ...defaults, definition: "SA node rhythm <60 bpm with normal P-QRS relationship.",
    diagnosticCriteria: ["HR <60 bpm", "Regular", "P before each QRS", "Normal PR and QRS"],
    ecgCharacteristics: ["Normal P morphology"], measurements: ["HR", "PR", "QTc"],
    differentialDiagnosis: ["Junctional rhythm", "AV block", "Medication effect"],
    pitfalls: ["Physiologic in athletes"], severity: "minor", urgency: "routine", riskCategory: "low",
    clinicalNotes: ["Evaluate if symptomatic"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("STACH", "Sinus Tachycardia", "rhythm", {
    ...defaults, definition: "SA node rhythm >100 bpm with normal conduction.",
    diagnosticCriteria: ["HR >100 bpm", "P before each QRS", "Gradual rate change typical"],
    ecgCharacteristics: ["Rate-dependent PR shortening"], measurements: ["HR", "PR"],
    differentialDiagnosis: ["SVT", "Atrial flutter", "Appropriate sinus tachycardia from fever/PE"],
    pitfalls: ["Always seek underlying cause"], severity: "minor", urgency: "routine", riskCategory: "low",
    clinicalNotes: ["Treat cause not rate alone"], guidelineReferences: [AHA_ECG],
  }),
  disease("AF", "Atrial Fibrillation", "rhythm", {
    ...defaults, evidenceLevel: "A", definition: "Chaotic atrial activity with irregular ventricular response.",
    diagnosticCriteria: ["Irregularly irregular RR", "Absent discrete P waves", "Fibrillatory baseline"],
    ecgCharacteristics: ["Variable RR", "No isoelectric baseline in atrial lead"],
    measurements: ["HR", "RR variability", "QRS width"], differentialDiagnosis: ["AFL with variable block", "Frequent PACs", "MAT"],
    pitfalls: ["WPW+AF dangerous with AV nodal blockers"], severity: "abnormal", urgency: "urgent", riskCategory: "high",
    recommendationLevel: "urgent", clinicalNotes: ["Stroke risk stratification", "Rate vs rhythm control"],
    guidelineReferences: [ACC_AHA_AF, AHA_ECG],
  }),
  disease("AFL", "Atrial Flutter", "rhythm", {
    ...defaults, definition: "Macro-reentrant atrial tachycardia ~250–350/min, often 2:1 AV conduction.",
    diagnosticCriteria: ["Sawtooth flutter waves", "Regular atrial activity", "Often fixed AV block ratio"],
    ecgCharacteristics: ["Negative sawtooth II, III, aVF"], measurements: ["Atrial rate", "Ventricular rate"],
    differentialDiagnosis: ["SVT", "Coarse AF"], pitfalls: ["2:1 block hides flutter waves"],
    severity: "abnormal", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["Ablation highly effective for typical flutter"], guidelineReferences: [ACC_AHA_AF],
  }),
  disease("SVT", "Supraventricular Tachycardia", "rhythm", {
    ...defaults, definition: "Regular narrow-complex tachycardia originating above ventricles.",
    diagnosticCriteria: ["Regular tachycardia", "QRS <120 ms typically", "Abrupt onset/offset"],
    ecgCharacteristics: ["P may be hidden in QRS/ST"], measurements: ["HR", "QRS duration"],
    differentialDiagnosis: ["Sinus tachycardia", "Atrial tachycardia", "AVNRT", "AVRT"],
    pitfalls: ["Wide-complex SVT treat as VT"], severity: "urgent", urgency: "urgent", riskCategory: "intermediate",
    recommendationLevel: "urgent", clinicalNotes: ["Vagal maneuvers, adenosine"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("AVNRT", "Atrioventricular Nodal Reentrant Tachycardia", "rhythm", {
    ...defaults, definition: "Most common PSVT due to dual AV nodal pathways.",
    diagnosticCriteria: ["Regular narrow QRS tachycardia 150–250 bpm", "P buried in or just after QRS"],
    ecgCharacteristics: ["Pseudo R' in V1", "RP < PR when P visible"], measurements: ["HR", "RP interval"],
    differentialDiagnosis: ["AVRT", "Atrial tachycardia", "Sinus tachycardia"], pitfalls: ["Adenosine diagnostic and therapeutic"],
    severity: "urgent", urgency: "urgent", riskCategory: "intermediate", recommendationLevel: "urgent",
    clinicalNotes: ["Catheter ablation curative"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("AVRT", "Atrioventricular Reentrant Tachycardia", "rhythm", {
    ...defaults, definition: "Reentry using accessory pathway (often WPW substrate).",
    diagnosticCriteria: ["Regular tachycardia", "Orthodromic: narrow QRS; Antidromic: wide QRS"],
    ecgCharacteristics: ["Retrograde P after QRS in orthodromic"], measurements: ["HR", "QRS width", "PR delta at baseline"],
    differentialDiagnosis: ["AVNRT", "VT", "Sinus tachycardia"], pitfalls: ["Avoid AV nodal blockers in antidromic AVRT/WPW"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["EP study for pathway mapping"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("PAC", "Premature Atrial Contraction", "rhythm", {
    ...defaults, definition: "Early atrial beat with non-sinus P morphology.",
    diagnosticCriteria: ["Early P wave", "Narrow QRS unless aberrancy", "Incomplete compensatory pause"],
    ecgCharacteristics: ["Abnormal P morphology", "May have Ashman aberrancy"], measurements: ["Coupling interval"],
    differentialDiagnosis: ["PVC", "Junctional premature beat"], pitfalls: ["Frequent PACs may precede AF"],
    severity: "minor", urgency: "routine", riskCategory: "low", clinicalNotes: ["Usually benign"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("PVC", "Premature Ventricular Contraction", "rhythm", {
    ...defaults, definition: "Early ventricular beat with wide QRS and full compensatory pause.",
    diagnosticCriteria: ["No preceding P", "Wide QRS >120 ms", "Full compensatory pause"],
    ecgCharacteristics: ["Bizarre QRS morphology", "Discordant ST-T"], measurements: ["QRS duration", "Coupling interval"],
    differentialDiagnosis: ["Aberrant PAC", "Pre-excited beat"], pitfalls: ["R-on-T in long QT"],
    severity: "minor", urgency: "routine", riskCategory: "low", clinicalNotes: ["Evaluate if frequent or symptomatic"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("VT", "Ventricular Tachycardia", "rhythm", {
    ...defaults, evidenceLevel: "A", definition: "Wide-complex tachycardia of ventricular origin ≥3 beats.",
    diagnosticCriteria: ["Wide QRS tachycardia", "AV dissociation if present", "Concordance in precordial leads"],
    ecgCharacteristics: ["Fusion/capture beats", "Northwest axis"], measurements: ["HR", "QRS duration"],
    differentialDiagnosis: ["SVT with aberrancy", "Antidromic WPW"], pitfalls: ["Treat as VT until proven otherwise"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Cardioversion if unstable", "Amiodarone/lidocaine per ACLS"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("VF", "Ventricular Fibrillation", "rhythm", {
    ...defaults, evidenceLevel: "A", definition: "Chaotic ventricular electrical activity without organized QRS.",
    diagnosticCriteria: ["No identifiable QRS", "Irregular chaotic waveform"],
    ecgCharacteristics: ["Coarse or fine fibrillation"], measurements: [],
    differentialDiagnosis: ["Fine VF vs asystole", "Artifact"], pitfalls: ["Confirm on multiple leads"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Immediate defibrillation"], guidelineReferences: [AHA_ECG],
  }),
  disease("ASYSTOLE", "Asystole", "rhythm", {
    ...defaults, definition: "Absence of ventricular electrical activity.",
    diagnosticCriteria: ["Flat line", "No QRS", "Confirm in multiple leads with gain"],
    ecgCharacteristics: ["Isoelectric baseline"], measurements: [],
    differentialDiagnosis: ["Fine VF", "Lead disconnect"], pitfalls: ["Always verify connections"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["CPR, epinephrine — not shockable"], guidelineReferences: [AHA_ECG],
  }),
  disease("PEA", "Pulseless Electrical Activity", "rhythm", {
    ...defaults, definition: "Organized ECG activity without palpable pulse.",
    diagnosticCriteria: ["Organized rhythm on monitor", "No pulse", "Excludes VF/pVT"],
    ecgCharacteristics: ["May show bradyarrhythmia or idioventricular pattern"], measurements: ["HR", "QRS width"],
    differentialDiagnosis: ["Severe hypotension", "True asystole"], pitfalls: ["Search reversible causes"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["5 Hs and 5 Ts"], guidelineReferences: [AHA_ECG],
  }),
  disease("AVB1", "First Degree AV Block", "conduction", {
    ...defaults, definition: "Prolonged PR with 1:1 AV conduction.",
    diagnosticCriteria: ["PR >200 ms", "Every P conducts"],
    ecgCharacteristics: ["Constant prolonged PR"], measurements: ["PR interval"],
    differentialDiagnosis: ["Enhanced AV conduction with long PR"], pitfalls: ["May progress in Lyme/degenerative disease"],
    severity: "minor", urgency: "routine", riskCategory: "low", clinicalNotes: ["Usually benign in isolation"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("AVB2I", "Second Degree AV Block Type I", "conduction", {
    ...defaults, definition: "Wenckebach — progressive PR prolongation until dropped beat.",
    diagnosticCriteria: ["Grouped beating", "Progressive PR lengthening", "Dropped QRS"],
    ecgCharacteristics: ["Narrow QRS usually"], measurements: ["PR pattern", "Conduction ratio"],
    differentialDiagnosis: ["Non-conducted PAC", "Mobitz II"], pitfalls: ["Usually AV nodal — often benign"],
    severity: "abnormal", urgency: "urgent", riskCategory: "intermediate", recommendationLevel: "urgent",
    clinicalNotes: ["Atropine if symptomatic"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("AVB2II", "Second Degree AV Block Type II", "conduction", {
    ...defaults, definition: "Fixed PR with sudden non-conducted P waves — infranodal.",
    diagnosticCriteria: ["Constant PR in conducted beats", "Sudden dropped QRS", "Often wide QRS"],
    ecgCharacteristics: ["Mobitz II pattern"], measurements: ["PR", "QRS duration"],
    differentialDiagnosis: ["Type I block", "Complete heart block"], pitfalls: ["Requires pacemaker"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["Permanent pacing indicated"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("AVB3", "Third Degree AV Block", "conduction", {
    ...defaults, definition: "Complete AV dissociation — atria and ventricles independent.",
    diagnosticCriteria: ["More P waves than QRS", "Variable PR", "Escape rhythm"],
    ecgCharacteristics: ["Junctional or ventricular escape"], measurements: ["Atrial rate", "Ventricular rate"],
    differentialDiagnosis: ["AV dissociation with acceleration"], pitfalls: ["Ventricular escape <40 unstable"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Emergency pacing if symptomatic"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("RBBB", "Right Bundle Branch Block", "conduction", {
    ...defaults, definition: "Delayed right ventricular depolarization — QRS ≥120 ms with rsR' V1.",
    diagnosticCriteria: ["QRS ≥120 ms", "rsR' in V1", "Wide S in I, V5–V6"],
    ecgCharacteristics: ["Terminal R in V1"], measurements: ["QRS duration"],
    differentialDiagnosis: ["RVH", "Brugada", "Posterior MI"], pitfalls: ["Incomplete RBBB 100–120 ms"],
    severity: "abnormal", urgency: "routine", riskCategory: "low", clinicalNotes: ["New RBBB with PE consider"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("LBBB", "Left Bundle Branch Block", "conduction", {
    ...defaults, definition: "Delayed left ventricular depolarization — broad R in lateral leads.",
    diagnosticCriteria: ["QRS ≥120 ms", "Dominant S V1", "Notched R I, aVL, V5–V6"],
    ecgCharacteristics: ["Discordant ST-T"], measurements: ["QRS duration", "Sgarbossa if ACS"],
    differentialDiagnosis: ["Ventricular rhythm", "Hyperkalemia"], pitfalls: ["Masks STEMI — use modified Sgarbossa"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Echo for new LBBB"],
    guidelineReferences: [AHA_ECG, UDMI],
  }),
  disease("LAFB", "Left Anterior Fascicular Block", "conduction", {
    ...defaults, definition: "Left anterior fascicle block — LAD −45° to −90° with narrow QRS.",
    diagnosticCriteria: ["LAD", "qR in aVL", "rS in II, III, aVF", "QRS <120 ms"],
    ecgCharacteristics: ["Left axis deviation"], measurements: ["Axis", "QRS duration"],
    differentialDiagnosis: ["LVH", "Inferior MI", "Normal variant in thin adults"], pitfalls: ["Part of bifascicular block"],
    severity: "minor", urgency: "routine", riskCategory: "low", clinicalNotes: ["Evaluate if bifascicular"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("LPFB", "Left Posterior Fascicular Block", "conduction", {
    ...defaults, definition: "Left posterior fascicle block — RAD +90° to +180° with narrow QRS.",
    diagnosticCriteria: ["RAD", "qR in III, aVF", "rS in I, aVL", "QRS <120 ms", "Exclude RVH/PE"],
    ecgCharacteristics: ["Right axis deviation without RVH"], measurements: ["Axis"],
    differentialDiagnosis: ["RVH", "Lateral MI", "Normal variant"], pitfalls: ["Diagnosis of exclusion"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Rare isolated finding"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("LVH", "Left Ventricular Hypertrophy", "hypertrophy", {
    ...defaults, definition: "Increased LV mass producing voltage and strain on ECG.",
    diagnosticCriteria: ["Sokolow-Lyon ≥35 mm", "Cornell criteria", "Strain pattern"],
    ecgCharacteristics: ["High QRS voltage", "ST-T strain lateral"], measurements: ["Sokolow-Lyon index"],
    differentialDiagnosis: ["Athletic heart", "Anterior MI", "LBBB"], pitfalls: ["Low sensitivity"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Echo confirms"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("RVH", "Right Ventricular Hypertrophy", "hypertrophy", {
    ...defaults, definition: "RV enlargement/pressure overload on ECG.",
    diagnosticCriteria: ["RAD", "R>S in V1", "P pulmonale", "Supporting criteria"],
    ecgCharacteristics: ["T inversion V1–V3"], measurements: ["Axis", "R/S V1"],
    differentialDiagnosis: ["Posterior MI", "RBBB", "WPW"], pitfalls: ["Acute RVH suggests PE/MI"],
    severity: "abnormal", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["Evaluate pulmonary hypertension"], guidelineReferences: [AHA_ECG],
  }),
  disease("STEMI", "ST-Elevation Myocardial Infarction", "ischemia", {
    ...defaults, evidenceLevel: "A", definition: "Acute myocardial injury with ST elevation meeting UDMI criteria.",
    diagnosticCriteria: ["ST ≥1 mm in ≥2 contiguous leads (≥2 mm V2–V3 men)", "New LBBB with ischemia = STEMI equivalent"],
    ecgCharacteristics: ["Hyperacute T waves early", "Reciprocal depression"], measurements: ["ST amplitude", "Territory"],
    differentialDiagnosis: ["Pericarditis", "Early repolarization", "LVH strain"], pitfalls: ["Posterior STEMI: ST dep V1–V3"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Activate cath lab", "Dual antiplatelet therapy"], guidelineReferences: [UDMI, ESC_ACS, AHA_ECG],
  }),
  disease("NSTEMI", "Non-ST-Elevation Myocardial Infarction", "ischemia", {
    ...defaults, evidenceLevel: "A", definition: "Acute MI without ST elevation meeting UDMI troponin criteria.",
    diagnosticCriteria: ["ST depression and/or T inversion", "Elevated troponin", "No ST elevation criteria for STEMI"],
    ecgCharacteristics: ["Dynamic ST-T changes"], measurements: ["ST deviation", "Troponin trend"],
    differentialDiagnosis: ["Stable angina", "Demand ischemia", "PE"], pitfalls: ["Wellens syndrome V2–V3"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["GRACE/TIMI risk stratification"], guidelineReferences: [UDMI, ESC_ACS],
  }),
  disease("ANT_MI", "Anterior Myocardial Infarction", "ischemia", {
    ...defaults, evidenceLevel: "A", definition: "STEMI/NSTEMI affecting LAD territory (V1–V4).",
    diagnosticCriteria: ["ST elevation V2–V4", "Q waves V1–V4", "Reciprocal changes inferior"],
    ecgCharacteristics: ["Hyperacute T V2–V4"], measurements: ["ST V1–V4"],
    differentialDiagnosis: ["LBBB", "Brugada", "Pericarditis"], pitfalls: ["Largest territory — high mortality"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["LAD occlusion — urgent reperfusion"], guidelineReferences: [UDMI, ESC_ACS],
  }),
  disease("INF_MI", "Inferior Myocardial Infarction", "ischemia", {
    ...defaults, evidenceLevel: "A", definition: "MI affecting RCA/LCx inferior territory (II, III, aVF).",
    diagnosticCriteria: ["ST elevation II, III, aVF", "Reciprocal ST dep I, aVL"],
    ecgCharacteristics: ["May include RV infarct V1 ST elevation"], measurements: ["ST inferior leads"],
    differentialDiagnosis: ["Pericarditis", "Early repolarization"], pitfalls: ["Check V4R for RV MI"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Avoid nitrates if RV infarct"], guidelineReferences: [UDMI, ESC_ACS],
  }),
  disease("LAT_MI", "Lateral Myocardial Infarction", "ischemia", {
    ...defaults, evidenceLevel: "A", definition: "MI affecting lateral wall (I, aVL, V5–V6).",
    diagnosticCriteria: ["ST elevation I, aVL, V5–V6"],
    ecgCharacteristics: ["Q waves lateral leads"], measurements: ["ST lateral leads"],
    differentialDiagnosis: ["LVH strain", "Pericarditis"], pitfalls: ["Often with inferior or anterior extension"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["LCx or wraparound LAD"], guidelineReferences: [UDMI, ESC_ACS],
  }),
  disease("POST_MI", "Posterior Myocardial Infarction", "ischemia", {
    ...defaults, evidenceLevel: "A", definition: "Posterior wall MI — often presents with anterior reciprocal changes.",
    diagnosticCriteria: ["ST depression V1–V3", "Tall R V1–V2", "Confirm with V7–V9 ST elevation"],
    ecgCharacteristics: ["Posterior ST elevation on V7–V9"], measurements: ["R wave V1–V2"],
    differentialDiagnosis: ["Anterior ischemia", "RVH"], pitfalls: ["Easy to miss without posterior leads"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Obtain V7–V9"], guidelineReferences: [UDMI, ESC_ACS],
  }),
  disease("HYPERK", "Hyperkalemia", "electrolyte", {
    ...defaults, definition: "Elevated serum K+ producing progressive ECG changes.",
    diagnosticCriteria: ["Peaked T waves", "PR prolongation", "QRS widening", "Sine wave pattern severe"],
    ecgCharacteristics: ["Tent-shaped T", "P wave loss"], measurements: ["T amplitude", "QRS width", "PR"],
    differentialDiagnosis: ["Early repolarization", "Hyperacute T STEMI"], pitfalls: ["ECG poorly correlates with K+ level"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "immediate",
    clinicalNotes: ["Calcium gluconate if ECG changes"], guidelineReferences: [AHA_ECG],
  }),
  disease("HYPOK", "Hypokalemia", "electrolyte", {
    ...defaults, definition: "Low serum K+ with repolarization abnormalities.",
    diagnosticCriteria: ["T flattening/inversion", "U waves", "ST depression", "QT prolongation"],
    ecgCharacteristics: ["Prominent U in V2–V3"], measurements: ["QU interval", "QTc"],
    differentialDiagnosis: ["Digoxin effect", "Long QT"], pitfalls: ["Arrhythmia risk during repletion"],
    severity: "abnormal", urgency: "urgent", riskCategory: "intermediate", recommendationLevel: "urgent",
    clinicalNotes: ["Replace K+ cautiously with monitoring"], guidelineReferences: [AHA_ECG],
  }),
  disease("HYPERCAL", "Hypercalcemia", "electrolyte", {
    ...defaults, definition: "Elevated Ca2+ shortening QT interval.",
    diagnosticCriteria: ["Short QT", "Short ST segment", "Normal T morphology typically"],
    ecgCharacteristics: ["QTc often <350 ms"], measurements: ["QT", "QTc"],
    differentialDiagnosis: ["Short QT syndrome", "Normal variant"], pitfalls: ["May predispose to arrhythmia"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Correct underlying cause"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("HYPOCAL", "Hypocalcemia", "electrolyte", {
    ...defaults, definition: "Low Ca2+ prolonging QT without primary T wave changes.",
    diagnosticCriteria: ["Prolonged QT", "Normal T wave morphology"],
    ecgCharacteristics: ["QT prolongation"], measurements: ["QTc"],
    differentialDiagnosis: ["Long QT syndrome", "Hypokalemia"], pitfalls: ["Torsades risk"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Replace Ca2+ and Mg2+"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("PERICARDITIS", "Pericarditis", "other", {
    ...defaults, definition: "Inflammation of pericardium with diffuse ECG changes.",
    diagnosticCriteria: ["Diffuse concave ST elevation", "PR depression", "Spodick sign", "No reciprocal ST dep except aVR/V1"],
    ecgCharacteristics: ["Four-stage evolution"], measurements: ["ST distribution", "PR segment"],
    differentialDiagnosis: ["STEMI", "Early repolarization"], pitfalls: ["Localized pericarditis mimics STEMI"],
    severity: "abnormal", urgency: "urgent", riskCategory: "intermediate", recommendationLevel: "urgent",
    clinicalNotes: ["NSAIDs and colchicine", "Exclude tamponade"], guidelineReferences: [ESC_ACS, AHA_ECG],
  }),
  disease("EARLY_REPOL", "Early Repolarization", "other", {
    ...defaults, definition: "Benign J-point elevation pattern in young individuals.",
    diagnosticCriteria: ["J-point elevation ≥1 mm in ≥2 leads", "Concave ST", "Stable pattern"],
    ecgCharacteristics: ["Slurring/notching at J point"], measurements: ["J-point amplitude"],
    differentialDiagnosis: ["Pericarditis", "STEMI", "Brugada type 2"], pitfalls: ["Inferior ER linked to VF in rare cases"],
    severity: "normal", urgency: "routine", riskCategory: "benign", clinicalNotes: ["Compare with prior ECGs"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("WPW", "Wolff-Parkinson-White Syndrome", "conduction", {
    ...defaults, definition: "Ventricular pre-excitation via accessory pathway.",
    diagnosticCriteria: ["Short PR <120 ms", "Delta wave", "Wide QRS"],
    ecgCharacteristics: ["Slurred upstroke QRS"], measurements: ["PR", "QRS", "Delta"],
    differentialDiagnosis: ["LBBB", "Hyperkalemia"], pitfalls: ["AF+WPW → rapid VF; no AV nodal blockers"],
    severity: "abnormal", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["EP referral for risk stratification"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("LONG_QT", "Long QT Syndrome", "channelopathy", {
    ...defaults, definition: "Prolonged repolarization predisposing to torsades de pointes.",
    diagnosticCriteria: ["QTc >470 ms male, >480 ms female", "LQT1–3 genetic subtypes"],
    ecgCharacteristics: ["Prolonged QT", "T wave abnormalities"], measurements: ["QTc Bazett/Fridericia"],
    differentialDiagnosis: ["Drug effect", "Hypocalcemia", "Hypokalemia"], pitfalls: ["Review QT-prolonging drugs"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["Correct electrolytes", "Beta-blockers in LQT1/2"], guidelineReferences: [AHA_ECG],
  }),
  disease("SHORT_QT", "Short QT Syndrome", "channelopathy", {
    ...defaults, definition: "Abbreviated repolarization with sudden death risk.",
    diagnosticCriteria: ["QTc ≤340 ms", "Tall peaked T", "Short ST segment"],
    ecgCharacteristics: ["Hyperacute T appearance"], measurements: ["QTc"],
    differentialDiagnosis: ["Hypercalcemia", "Normal variant"], pitfalls: ["Rare — may be missed"],
    severity: "abnormal", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["Family screening", "ICD if high risk"], guidelineReferences: [AHA_ECG],
  }),
  disease("BRUGADA", "Brugada Syndrome", "channelopathy", {
    ...defaults, definition: "Channelopathy with coved ST elevation V1–V3 and VF risk.",
    diagnosticCriteria: ["Type 1: coved ST ≥2 mm V1–V3 + negative T", "Spontaneous or drug-induced"],
    ecgCharacteristics: ["RBBB-like pattern V1–V2"], measurements: ["ST amplitude V1–V3"],
    differentialDiagnosis: ["RBBB", "Early repolarization", "ARVC"], pitfalls: ["Intermittent pattern"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["ICD if high risk or prior arrest"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("ARVC", "Arrhythmogenic Right Ventricular Cardiomyopathy", "structural", {
    ...defaults, definition: "Fibrofatty replacement of RV myocardium with arrhythmia and sudden death risk.",
    diagnosticCriteria: ["Epsilon waves", "T inversion V1–V3", "PVC with LBBB morphology", "Prolonged S wave V1–V3"],
    ecgCharacteristics: ["Terminal activation delay V1–V3"], measurements: ["S wave duration V1–V3"],
    differentialDiagnosis: ["Brugada", "RBBB", "RVH"], pitfalls: ["Task Force criteria require imaging"],
    severity: "urgent", urgency: "urgent", riskCategory: "high", recommendationLevel: "urgent",
    clinicalNotes: ["MRI and genetic testing"], guidelineReferences: [ESC_SYNC, AHA_ECG],
  }),
  disease("PACEMAKER", "Pacemaker Rhythms", "device", {
    ...defaults, definition: "Cardiac pacing with visible spikes and captured beats.",
    diagnosticCriteria: ["Pacing spikes before P or QRS", "Capture with appropriate morphology"],
    ecgCharacteristics: ["Spike artifact", "Wide QRS if ventricular pacing"], measurements: ["Pacing rate", "Capture"],
    differentialDiagnosis: ["Artifact", "Pre-excitation"], pitfalls: ["Failure to capture/sense"],
    severity: "minor", urgency: "routine", riskCategory: "low", clinicalNotes: ["Device interrogation"],
    guidelineReferences: [AHA_ECG, IEC],
  }),
  disease("BBB_ESCAPE", "Bundle Branch Escape", "rhythm", {
    ...defaults, definition: "Escape rhythm originating from damaged bundle branches.",
    diagnosticCriteria: ["Wide QRS escape 20–40 bpm", "Follows complete AV block"],
    ecgCharacteristics: ["BBB morphology at slow rate"], measurements: ["HR", "QRS width"],
    differentialDiagnosis: ["Ventricular escape", "Junctional escape with BBB"], pitfalls: ["Unstable — pacing needed"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Temporary then permanent pacing"], guidelineReferences: [AHA_ECG, ESC_SYNC],
  }),
  disease("JUNCTIONAL", "Junctional Rhythm", "rhythm", {
    ...defaults, definition: "AV junction pacemaker rhythm 40–60 bpm.",
    diagnosticCriteria: ["Narrow QRS", "Retrograde or absent P", "Rate 40–60"],
    ecgCharacteristics: ["P may be inverted in II before/after QRS"], measurements: ["HR", "PR"],
    differentialDiagnosis: ["Sinus bradycardia", "Complete heart block with escape"], pitfalls: ["Accelerated junctional 60–100"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Evaluate AV node function"],
    guidelineReferences: [AHA_ECG],
  }),
  disease("IVR", "Idioventricular Rhythm", "rhythm", {
    ...defaults, definition: "Slow ventricular escape 20–40 bpm without P waves.",
    diagnosticCriteria: ["Wide QRS", "Rate 20–40", "No P waves"],
    ecgCharacteristics: ["Bizarre QRS morphology"], measurements: ["HR", "QRS duration"],
    differentialDiagnosis: ["Ventricular escape post-arrest", "PEA"], pitfalls: ["Pre-terminal rhythm"],
    severity: "critical", urgency: "critical", riskCategory: "critical", recommendationLevel: "immediate",
    clinicalNotes: ["Atropine/pacing if symptomatic"], guidelineReferences: [AHA_ECG],
  }),
  disease("AIVR", "Accelerated Idioventricular Rhythm", "rhythm", {
    ...defaults, definition: "Ventricular rhythm 60–100 bpm — reperfusion arrhythmia post-MI.",
    diagnosticCriteria: ["Wide QRS", "Rate 60–100", "Gradual onset/offset", "Fusion beats"],
    ecgCharacteristics: ["Slow VT appearance"], measurements: ["HR", "QRS width"],
    differentialDiagnosis: ["VT", "SVT with aberrancy"], pitfalls: ["Benign post-reperfusion — do not treat if stable"],
    severity: "abnormal", urgency: "routine", riskCategory: "intermediate", clinicalNotes: ["Often self-limiting post-MI"],
    guidelineReferences: [AHA_ECG, UDMI],
  }),
];

export const EMKP_CATEGORIES: EmkpKnowledgeCategory[] = [
  "normal", "rhythm", "conduction", "ischemia", "electrolyte", "hypertrophy", "channelopathy", "structural", "device", "other",
];

export { AHA_ECG, ESC_ACS, ACC_AHA_AF, UDMI, ESC_SYNC, IEC };
