import { z } from "zod";

export const patientBodySchema = z.object({
  address: z.string().trim().max(500).optional(),
  alcoholStatus: z.string().trim().max(80).optional(),
  allergies: z.string().trim().max(1000).optional(),
  arrhythmiaHistoryFlag: z.boolean().optional(),
  bloodGroup: z.string().trim().max(20).optional(),
  bmi: z.coerce.number().positive().optional(),
  company: z.string().trim().max(160).optional(),
  cardiovascularHistory: z.string().trim().max(3000).optional(),
  contractorName: z.string().trim().max(160).optional(),
  contractorCompanyId: z.string().trim().optional(),
  contractorId: z.string().trim().optional(),
  dateOfBirth: z.coerce.date(),
  departmentId: z.string().trim().optional(),
  departmentName: z.string().trim().max(160).optional(),
  diabetes: z.boolean().optional(),
  dyslipidemia: z.boolean().optional(),
  email: z.string().email().optional(),
  employeeId: z.string().trim().max(80).optional(),
  emergencyContact: z.string().trim().max(250).optional(),
  emergencyContactName: z.string().trim().max(160).optional(),
  emergencyContactPhone: z.string().trim().max(40).optional(),
  familyHistory: z.string().trim().max(2000).optional(),
  firstName: z.string().trim().min(1).max(80),
  fullName: z.string().trim().max(240).optional(),
  gender: z.enum(["male", "female", "child", "child_male", "child_female", "other", "unknown"]),
  heartFailure: z.boolean().optional(),
  heightCm: z.coerce.number().positive().optional(),
  hireDate: z.coerce.date().optional(),
  hypertension: z.boolean().optional(),
  ischemicHeartDisease: z.boolean().optional(),
  jobTitle: z.string().trim().max(160).optional(),
  knownAllergies: z.string().trim().max(1000).optional(),
  lastName: z.string().trim().min(1).max(80),
  maritalStatus: z.string().trim().max(80).optional(),
  medicalHistory: z.string().trim().max(3000).optional(),
  medicalRecordNumber: z.string().trim().min(1).max(80),
  medications: z.string().trim().max(2000).optional(),
  middleName: z.string().trim().max(80).optional(),
  nationalId: z.string().trim().max(80).optional(),
  notes: z.string().trim().max(3000).optional(),
  obesity: z.boolean().optional(),
  occupation: z.string().trim().max(160).optional(),
  organizationId: z.string().trim().optional(),
  passportNumber: z.string().trim().max(80).optional(),
  phone: z.string().trim().max(40).optional(),
  previousCABG: z.boolean().optional(),
  previousMI: z.boolean().optional(),
  previousPCI: z.boolean().optional(),
  smokingStatus: z.enum(["never", "former", "current", "unknown"]).optional(),
  status: z.enum(["active", "inactive"]).optional(),
  stentsHistory: z.string().trim().max(2000).optional(),
  weightKg: z.coerce.number().positive().optional(),
});

export const patientUpdateSchema = patientBodySchema.partial();

export const patientListSchema = z.object({
  archived: z.enum(["true", "false", "all"]).default("false"),
  contractorId: z.string().trim().optional(),
  dateFrom: z.coerce.date().optional(),
  dateTo: z.coerce.date().optional(),
  diagnosis: z.string().trim().optional(),
  employeeId: z.string().trim().optional(),
  gender: z.enum(["male", "female", "child", "child_male", "child_female", "other", "unknown"]).optional(),
  nationalId: z.string().trim().optional(),
  organizationId: z.string().trim().optional(),
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),
  q: z.string().trim().optional(),
  sortBy: z.enum(["age", "createdAt", "employeeId", "fullName", "lastEcgDate", "patientCode", "status"]).default("createdAt"),
  sortDir: z.enum(["asc", "desc"]).default("desc"),
  status: z.enum(["active", "inactive"]).optional(),
});
