INSERT INTO "ECGKnowledgeEntry" ("id", "topic", "category", "content", "references", "tags", "updatedAt")
VALUES
  ('ecg_rag_normal_ecg', 'Normal ECG', 'Core Interpretation', 'Definition: sinus rhythm with normal rate, axis, intervals, R-wave progression, and no clinically significant ST-T abnormality. ECG criteria: P before every QRS, PR 120-200 ms, QRS <120 ms, QTc within accepted range, no pathologic Q waves or acute ischemic changes. Differential diagnosis: normal variant, early repolarization, artifact. Clinical significance: low immediate ECG risk when symptoms and history are reassuring. Occupational implications: generally fit if asymptomatic and no high-risk job-specific concern. Recommended follow-up: routine surveillance when clinically indicated.', ARRAY['AHA standardized ECG interpretation'], ARRAY['normal','sinus','fitness','follow-up'], CURRENT_TIMESTAMP),
  ('ecg_rag_sinus_bradycardia', 'Sinus Bradycardia', 'Arrhythmias', 'Definition: sinus rhythm with rate below 60 bpm. ECG criteria: sinus P waves with constant PR and narrow QRS unless conduction disease coexists. Differential diagnosis: athletic conditioning, medications, hypothyroidism, ischemia, high vagal tone, AV block. Clinical significance: risk depends on symptoms, pauses, hypotension, and conduction disease. Occupational implications: safety-sensitive work requires symptom review and cause assessment. Recommended follow-up: medication review, vitals, electrolytes, thyroid testing, Holter if symptomatic.', ARRAY['AHA bradycardia guidance'], ARRAY['bradycardia','sinus','occupational'], CURRENT_TIMESTAMP),
  ('ecg_rag_sinus_tachycardia', 'Sinus Tachycardia', 'Arrhythmias', 'Definition: sinus rhythm with rate above 100 bpm. ECG criteria: sinus P wave before each QRS with regular rhythm. Differential diagnosis: fever, anemia, pain, anxiety, dehydration, PE, hyperthyroidism, stimulant use. Clinical significance: usually secondary and requires cause evaluation. Occupational implications: fitness depends on underlying cause and hemodynamic stability. Recommended follow-up: vitals, oxygen saturation, CBC, thyroid, infection and cardiopulmonary assessment.', ARRAY['AHA ECG interpretation standards'], ARRAY['tachycardia','sinus','risk'], CURRENT_TIMESTAMP),
  ('ecg_rag_af', 'Atrial Fibrillation', 'Arrhythmias', 'Definition: irregularly irregular atrial rhythm without consistent P waves. ECG criteria: absent organized P waves, irregular RR intervals, variable ventricular response. Differential diagnosis: atrial flutter with variable block, frequent PACs, artifact. Clinical significance: stroke risk, rate-related symptoms, heart failure risk. Occupational implications: safety-sensitive workers need rate control, symptom assessment, anticoagulation decision, and physician clearance. Recommended follow-up: CHA2DS2-VASc assessment, echo, thyroid/electrolytes, rate/rhythm management.', ARRAY['ESC AF guideline'], ARRAY['af','atrial','fibrillation','stroke','occupational'], CURRENT_TIMESTAMP),
  ('ecg_rag_atrial_flutter', 'Atrial Flutter', 'Arrhythmias', 'Definition: macroreentrant atrial tachyarrhythmia often with sawtooth flutter waves. ECG criteria: flutter waves commonly in inferior leads, atrial rate near 250-350 bpm, fixed or variable AV block. Differential diagnosis: AF, atrial tachycardia, SVT. Clinical significance: thromboembolic and tachycardia-mediated cardiomyopathy risk. Occupational implications: restrict high-risk duty if rapid, symptomatic, or uncontrolled. Recommended follow-up: anticoagulation assessment, rate/rhythm control, EP referral when indicated.', ARRAY['ESC supraventricular tachycardia guideline'], ARRAY['flutter','atrial','tachycardia'], CURRENT_TIMESTAMP),
  ('ecg_rag_pac', 'Premature Atrial Complexes', 'Arrhythmias', 'Definition: premature atrial beats arising outside the sinus node. ECG criteria: early abnormal P wave, usually narrow QRS, non-compensatory pause. Differential diagnosis: PVC with narrow morphology, artifact, sinus arrhythmia. Clinical significance: usually benign but frequent PACs can predict AF risk. Occupational implications: usually fit if asymptomatic and no structural disease. Recommended follow-up: symptom assessment, triggers, Holter if frequent or symptomatic.', ARRAY['AHA arrhythmia reviews'], ARRAY['pac','premature','atrial'], CURRENT_TIMESTAMP),
  ('ecg_rag_pvc', 'Premature Ventricular Complexes', 'Arrhythmias', 'Definition: premature ventricular depolarizations. ECG criteria: early wide QRS without preceding P wave, discordant ST-T, compensatory pause. Differential diagnosis: aberrant PAC, artifact, ventricular escape. Clinical significance: depends on burden, morphology, symptoms, and structural heart disease. Occupational implications: safety-sensitive workers need evaluation if frequent, complex, symptomatic, or exercise-induced. Recommended follow-up: electrolytes, echo, Holter, stress testing when indicated.', ARRAY['AHA ventricular arrhythmia guidance'], ARRAY['pvc','ventricular','occupational'], CURRENT_TIMESTAMP),
  ('ecg_rag_av_blocks', 'AV Blocks', 'Conduction', 'Definition: delayed or interrupted atrioventricular conduction. ECG criteria: first degree PR >200 ms, second degree dropped QRS, third degree AV dissociation. Differential diagnosis: vagal tone, medications, ischemia, degenerative conduction disease. Clinical significance: high-grade block can cause syncope and sudden incapacity. Occupational implications: high-grade or symptomatic block is unfit for safety-sensitive duty pending treatment. Recommended follow-up: medication/electrolyte review, urgent assessment for high-grade block, pacemaker evaluation when indicated.', ARRAY['AHA bradycardia guideline'], ARRAY['av block','heart block','conduction','bradycardia'], CURRENT_TIMESTAMP),
  ('ecg_rag_bundle_branch_blocks', 'Bundle Branch Blocks', 'Conduction', 'Definition: delayed conduction in right or left bundle branch. ECG criteria: QRS >=120 ms with RBBB or LBBB morphology. Differential diagnosis: ventricular pacing, nonspecific IVCD, hyperkalemia, ventricular rhythm. Clinical significance: new LBBB/RBBB may indicate structural disease or ischemia depending on context. Occupational implications: evaluate symptoms, structural heart disease, and newness before safety-sensitive clearance. Recommended follow-up: compare prior ECGs, echo, ischemia workup if clinically indicated.', ARRAY['AHA intraventricular conduction recommendations'], ARRAY['rbbb','lbbb','bundle','qrs'], CURRENT_TIMESTAMP),
  ('ecg_rag_stemi', 'STEMI', 'Ischemia', 'Definition: acute coronary occlusion pattern with ST elevation in a vascular territory. ECG criteria: contiguous ST elevation meeting age/sex/lead thresholds with reciprocal changes or compatible clinical picture. Differential diagnosis: early repolarization, pericarditis, LVH, LBBB, ventricular aneurysm. Clinical significance: emergency condition requiring immediate reperfusion pathway. Occupational implications: temporarily unfit for all safety-sensitive work until acute event is excluded/treated and clearance obtained. Recommended follow-up: immediate ER/cardiology activation, serial ECGs, troponin, reperfusion protocol.', ARRAY['Fourth Universal Definition of MI', 'AHA STEMI systems of care'], ARRAY['stemi','st elevation','ischemia','critical'], CURRENT_TIMESTAMP),
  ('ecg_rag_nstemi', 'NSTEMI', 'Ischemia', 'Definition: myocardial infarction without diagnostic ST elevation, requiring biomarkers and clinical assessment. ECG criteria: ST depression, T inversion, dynamic changes, or sometimes normal ECG. Differential diagnosis: demand ischemia, LVH strain, electrolyte abnormality, digoxin effect. Clinical significance: high-risk ACS spectrum. Occupational implications: unfit for safety-sensitive work during evaluation and until cardiology clearance. Recommended follow-up: serial troponin, serial ECG, risk scoring, cardiology referral.', ARRAY['ESC ACS guideline'], ARRAY['nstemi','troponin','st depression','ischemia'], CURRENT_TIMESTAMP),
  ('ecg_rag_ischemia', 'Ischemia', 'Ischemia', 'Definition: ECG evidence of insufficient myocardial oxygen supply. ECG criteria: ST depression, T-wave inversion, transient ST elevation, dynamic changes. Differential diagnosis: LVH strain, bundle branch block, electrolyte changes, medication effects. Clinical significance: may represent ACS or chronic coronary disease. Occupational implications: restrict safety-sensitive duties until symptomatic and ischemic risk is clarified. Recommended follow-up: symptoms/vitals, troponin, stress imaging or coronary assessment based on risk.', ARRAY['AHA ischemia ECG standards'], ARRAY['ischemia','st depression','t wave'], CURRENT_TIMESTAMP),
  ('ecg_rag_lvh', 'Left Ventricular Hypertrophy', 'Chamber Enlargement', 'Definition: increased LV mass suggested by ECG voltage/repolarization criteria. ECG criteria: high QRS voltage, strain pattern, left axis or LA abnormality depending criteria. Differential diagnosis: normal young/athletic voltage, conduction disease, ischemia. Clinical significance: hypertension target organ damage and cardiovascular risk marker. Occupational implications: usually not automatically unfit but needs BP control and structural assessment if severe. Recommended follow-up: blood pressure control, echocardiography, risk factor management.', ARRAY['AHA chamber enlargement recommendations'], ARRAY['lvh','hypertrophy','hypertension'], CURRENT_TIMESTAMP),
  ('ecg_rag_rvh', 'Right Ventricular Hypertrophy', 'Chamber Enlargement', 'Definition: increased RV forces often related to pulmonary or congenital disease. ECG criteria: right axis deviation, dominant R in V1, right precordial strain. Differential diagnosis: posterior MI, RBBB, normal variant, lead misplacement. Clinical significance: may indicate pulmonary hypertension or RV pressure overload. Occupational implications: evaluate exertional capacity and hypoxia risk for demanding/offshore work. Recommended follow-up: echo, oxygen saturation, pulmonary assessment.', ARRAY['AHA chamber enlargement recommendations'], ARRAY['rvh','right axis','pulmonary'], CURRENT_TIMESTAMP),
  ('ecg_rag_hyperkalemia', 'Hyperkalemia', 'Electrolyte', 'Definition: elevated serum potassium with progressive ECG toxicity. ECG criteria: peaked T waves, PR prolongation, P flattening, QRS widening, sine-wave pattern. Differential diagnosis: early repolarization, STEMI, LVH repolarization. Clinical significance: can progress to fatal arrhythmia. Occupational implications: unfit during acute electrolyte instability. Recommended follow-up: urgent potassium confirmation and emergency treatment when ECG toxicity suspected.', ARRAY['Emergency ECG electrolyte reviews'], ARRAY['hyperkalemia','potassium','qrs','critical'], CURRENT_TIMESTAMP),
  ('ecg_rag_hypokalemia', 'Hypokalemia', 'Electrolyte', 'Definition: low serum potassium affecting repolarization. ECG criteria: ST depression, T flattening, prominent U waves, apparent QT/QU prolongation. Differential diagnosis: ischemia, medication effect, long QT syndrome. Clinical significance: arrhythmia risk especially with QT-prolonging drugs. Occupational implications: restrict high-risk duty if symptomatic, severe, or arrhythmogenic. Recommended follow-up: potassium/magnesium correction, medication review, repeat ECG.', ARRAY['Emergency ECG electrolyte reviews'], ARRAY['hypokalemia','potassium','u wave','qt'], CURRENT_TIMESTAMP),
  ('ecg_rag_qt_abnormalities', 'QT Abnormalities', 'Repolarization', 'Definition: abnormal ventricular repolarization duration. ECG criteria: prolonged or shortened QTc after accurate measurement and rate correction. Differential diagnosis: medication effect, electrolyte disturbance, congenital syndrome, ischemia, bradycardia. Clinical significance: prolonged QTc increases torsades risk. Occupational implications: safety-sensitive work requires risk assessment if marked QTc prolongation, syncope, or family history. Recommended follow-up: medication/electrolyte review, repeat ECG, cardiology/genetic evaluation when indicated.', ARRAY['AHA QT interval recommendations'], ARRAY['qt','qtc','torsades','repolarization'], CURRENT_TIMESTAMP),
  ('ecg_rag_pericarditis', 'Pericarditis', 'ST-T Patterns', 'Definition: pericardial inflammation with characteristic ECG evolution. ECG criteria: diffuse concave ST elevation, PR depression, absence of territorial reciprocal changes except aVR/V1. Differential diagnosis: STEMI, early repolarization, myocarditis. Clinical significance: usually inflammatory but may involve myocardium or effusion. Occupational implications: restrict strenuous/safety-sensitive work until symptoms and inflammation resolve. Recommended follow-up: clinical evaluation, troponin/CRP, echo if effusion suspected.', ARRAY['ESC pericardial disease guideline'], ARRAY['pericarditis','st elevation','pr depression'], CURRENT_TIMESTAMP),
  ('ecg_rag_early_repolarization', 'Early Repolarization', 'ST-T Patterns', 'Definition: benign repolarization variant commonly seen in younger healthy adults. ECG criteria: J-point elevation, concave ST elevation, stable pattern, no reciprocal ischemic changes. Differential diagnosis: STEMI, pericarditis, Brugada pattern. Clinical significance: usually benign but must be interpreted with symptoms and serial ECGs. Occupational implications: generally fit if asymptomatic and acute ischemia excluded. Recommended follow-up: compare prior ECGs and evaluate symptoms before clearance.', ARRAY['AHA ST elevation differential reviews'], ARRAY['early repolarization','st elevation','normal variant'], CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET
  "topic" = EXCLUDED."topic",
  "category" = EXCLUDED."category",
  "content" = EXCLUDED."content",
  "references" = EXCLUDED."references",
  "tags" = EXCLUDED."tags",
  "updatedAt" = CURRENT_TIMESTAMP;
