ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'ST_ELEVATION';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'ST_DEPRESSION';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'T_INVERSION';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'PVC';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'ATRIAL_FIBRILLATION';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'BRADYCARDIA';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'TACHYCARDIA';
ALTER TYPE "ECGAnnotationType" ADD VALUE IF NOT EXISTS 'QT_PROLONGATION';

ALTER TABLE "ECGLeadSignal" ADD COLUMN IF NOT EXISTS "paperSpeed" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "ECGLeadSignal" ADD COLUMN IF NOT EXISTS "gain" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "ECGLeadSignal" ADD COLUMN IF NOT EXISTS "metadataJson" JSONB;
