import type {
  EcgClinicalKnowledgeCategory,
  EcgClinicalKnowledgeEmergencyLevel,
  EcgClinicalKnowledgeSeverity,
} from "@prisma/client";
import type { EcgClinicalKnowledgeEntry, GuidelineReference, LiteratureReference } from "./types";

const AHA_ECG: GuidelineReference = { organization: "ACC/AHA", title: "AHA/ACC/HRS Recommendations for ECG Interpretation", year: 2022 };
const ESC_AF: GuidelineReference = { organization: "ESC", title: "2024 ESC Guidelines for atrial fibrillation", year: 2024 };
const ESC_ACS: GuidelineReference = { organization: "ESC", title: "2023 ESC Guidelines for acute coronary syndromes", year: 2023 };
const ESC_SYNC: GuidelineReference = { organization: "ESC", title: "2021 ESC Guidelines on cardiac pacing and syncope", year: 2021 };
const AHA_STEMI: GuidelineReference = { organization: "ACC/AHA", title: "2023 ACC/AHA STEMI guideline update", year: 2023 };

function ref(citation: string, source?: string, year?: number): LiteratureReference {
  return { citation, source, year };
}

function k(
  diagnosisId: string,
  clinicalName: string,
  category: EcgClinicalKnowledgeCategory,
  severity: EcgClinicalKnowledgeSeverity,
  emergencyLevel: EcgClinicalKnowledgeEmergencyLevel,
  description: string,
  fields: Partial<
    Pick<
      EcgClinicalKnowledgeEntry,
      | "ecgCriteria"
      | "diagnosticFeatures"
      | "supportingLeads"
      | "differentialDiagnoses"
      | "recommendedNextTests"
      | "recommendedManagement"
      | "contraindications"
      | "clinicalNotes"
      | "references"
      | "icd10Code"
      | "snomedCode"
      | "guidelineReferences"
    >
  > = {},
): EcgClinicalKnowledgeEntry {
  return {
    clinicalName,
    category,
    contraindications: fields.contraindications ?? [],
    description,
    diagnosisId,
    diagnosticFeatures: fields.diagnosticFeatures ?? [],
    differentialDiagnoses: fields.differentialDiagnoses ?? [],
    ecgCriteria: fields.ecgCriteria ?? [],
    emergencyLevel,
    guidelineReferences: fields.guidelineReferences ?? [AHA_ECG],
    icd10Code: fields.icd10Code,
    clinicalNotes: fields.clinicalNotes ?? [],
    recommendedManagement: fields.recommendedManagement ?? [],
    recommendedNextTests: fields.recommendedNextTests ?? [],
    references: fields.references ?? [ref(`${clinicalName} — structured ECG clinical knowledge entry`, "ECG Insight Clinical Knowledge Engine", 2026)],
    severity,
    snomedCode: fields.snomedCode,
    supportingLeads: fields.supportingLeads ?? [],
  };
}

export const ECG_CLINICAL_KNOWLEDGE_CATALOG: EcgClinicalKnowledgeEntry[] = [
  k("SINUS_RHYTHM", "Sinus Rhythm", "RHYTHM", "NORMAL", "ROUTINE",
    "Regular cardiac rhythm originating from the sinoatrial node with normal rate and conduction.",
    {
      ecgCriteria: ["P wave before each QRS with consistent morphology", "P axis +45° to +75° in limb leads", "Constant PR interval", "Rate 60–100 bpm in adults"],
      diagnosticFeatures: ["Regular R-R intervals", "Upright P in I and II", "Normal PR, QRS, and QT intervals"],
      supportingLeads: ["I", "II", "aVF", "V1–V6"],
      differentialDiagnoses: ["Sinus arrhythmia", "Ectopic atrial rhythm"],
      recommendedNextTests: ["None if asymptomatic and no clinical concern"],
      recommendedManagement: ["Document as baseline when clinically appropriate"],
      icd10Code: "R00.8", snomedCode: "426783006", guidelineReferences: [AHA_ECG],
    }),
  k("SINUS_BRADYCARDIA", "Sinus Bradycardia", "ARRHYTHMIA", "MINOR", "ROUTINE",
    "Sinus rhythm with ventricular rate below 60 bpm in adults.",
    {
      ecgCriteria: ["Normal P wave morphology", "Rate <60 bpm", "Each P followed by QRS"],
      diagnosticFeatures: ["Prolonged R-R intervals", "Normal PR and QRS duration"],
      supportingLeads: ["II", "V1"],
      differentialDiagnoses: ["Junctional rhythm", "Second-degree AV block", "Sinus pause"],
      recommendedNextTests: ["Holter monitor if symptomatic", "Thyroid function", "Electrolytes"],
      recommendedManagement: ["Review medications (beta-blockers, CCBs)", "Treat underlying cause if pathologic"],
      clinicalNotes: ["Physiologic in athletes and during sleep"],
      icd10Code: "R00.1", snomedCode: "426177001", guidelineReferences: [AHA_ECG, ESC_SYNC],
    }),
  k("SINUS_TACHYCARDIA", "Sinus Tachycardia", "ARRHYTHMIA", "ABNORMAL", "URGENT",
    "Sinus rhythm with ventricular rate above 100 bpm in adults.",
    {
      ecgCriteria: ["Upright P in I and II", "Rate >100 bpm", "Each P followed by QRS"],
      diagnosticFeatures: ["Shortened R-R intervals", "Normal QRS morphology"],
      supportingLeads: ["II", "V1"],
      differentialDiagnoses: ["Atrial flutter with 2:1 block", "SVT", "Atrial tachycardia"],
      recommendedNextTests: ["CBC", "Troponin if chest pain", "Chest imaging if dyspnea"],
      recommendedManagement: ["Treat underlying cause (fever, hypovolemia, pain, PE)"],
      icd10Code: "R00.0", snomedCode: "11092001", guidelineReferences: [AHA_ECG],
    }),
  k("ATRIAL_FIBRILLATION", "Atrial Fibrillation", "ARRHYTHMIA", "URGENT", "URGENT",
    "Chaotic atrial activity with irregularly irregular ventricular response and absent discrete P waves.",
    {
      ecgCriteria: ["Irregularly irregular R-R", "No consistent P waves", "Fibrillatory baseline may be present"],
      diagnosticFeatures: ["Absent P waves", "Variable ventricular rate", "Irregular rhythm"],
      supportingLeads: ["II", "V1", "aVF"],
      differentialDiagnoses: ["Atrial flutter with variable block", "Multifocal atrial tachycardia", "Frequent PACs"],
      recommendedNextTests: ["Echocardiography", "TSH", "CHA2DS2-VASc assessment"],
      recommendedManagement: ["Rate or rhythm control", "Anticoagulation per stroke risk", "Cardiology referral"],
      contraindications: ["AV nodal blockers in pre-excited AF (WPW)"],
      clinicalNotes: ["Assess hemodynamic stability first"],
      icd10Code: "I48.91", snomedCode: "49436004", guidelineReferences: [ESC_AF, AHA_ECG],
    }),
  k("ATRIAL_FLUTTER", "Atrial Flutter", "ARRHYTHMIA", "URGENT", "URGENT",
    "Macro-reentrant atrial tachycardia with sawtooth flutter waves and regular atrial rate near 300 bpm.",
    {
      ecgCriteria: ["Atrial rate ~250–350 bpm", "Sawtooth F waves in II, III, aVF", "Ventricular response often 2:1 or 4:1"],
      diagnosticFeatures: ["Sawtooth pattern", "Regular or regularly irregular ventricular response"],
      supportingLeads: ["II", "III", "aVF", "V1"],
      differentialDiagnoses: ["Atrial fibrillation", "SVT", "Sinus tachycardia with artifact"],
      recommendedNextTests: ["Echocardiography", "Anticoagulation assessment"],
      recommendedManagement: ["Rate control", "Consider cardioversion or ablation"],
      icd10Code: "I48.92", snomedCode: "5370000", guidelineReferences: [ESC_AF, AHA_ECG],
    }),
  k("SVT", "Supraventricular Tachycardia", "ARRHYTHMIA", "URGENT", "EMERGENT",
    "Paroxysmal narrow-complex tachycardia originating above the ventricles, typically regular and rapid.",
    {
      ecgCriteria: ["Rate usually 150–250 bpm", "Narrow QRS unless aberrancy", "Abrupt onset and termination when paroxysmal"],
      diagnosticFeatures: ["Regular tachycardia", "P waves may be hidden in ST segment or T wave"],
      supportingLeads: ["II", "V1", "aVR"],
      differentialDiagnoses: ["Sinus tachycardia", "Atrial flutter", "Atrial tachycardia", "Junctional tachycardia"],
      recommendedNextTests: ["Electrolytes", "EP study if recurrent"],
      recommendedManagement: ["Vagal maneuvers if stable", "Adenosine per ACLS", "Cardiology/EP referral"],
      contraindications: ["Verapamil/diltiazem in WPW with AF"],
      clinicalNotes: ["Avoid AV nodal blockers in pre-excited tachycardia"],
      icd10Code: "I47.1", snomedCode: "6456007", guidelineReferences: [AHA_ECG, ESC_SYNC],
    }),
  k("VT", "Ventricular Tachycardia", "ARRHYTHMIA", "CRITICAL", "CRITICAL",
    "Three or more consecutive ventricular beats at rate typically >100 bpm with wide QRS morphology.",
    {
      ecgCriteria: ["Wide QRS tachycardia", "AV dissociation may be present", "Fusion and capture beats support VT"],
      diagnosticFeatures: ["Wide regular or irregular tachycardia", "Concordance in precordial leads", "Northwest axis"],
      supportingLeads: ["V1", "V6", "aVR"],
      differentialDiagnoses: ["SVT with aberrancy", "Antidromic WPW", "Pacemaker-mediated tachycardia"],
      recommendedNextTests: ["Electrolytes", "Troponin", "Echocardiography", "Coronary angiography if ischemic"],
      recommendedManagement: ["Immediate ACLS", "Defibrillation if pulseless", "Amiodarone/lidocaine per protocol", "ICD evaluation"],
      icd10Code: "I47.2", snomedCode: "25569003", guidelineReferences: [AHA_ECG, ESC_ACS],
    }),
  k("VF", "Ventricular Fibrillation", "ARRHYTHMIA", "CRITICAL", "CRITICAL",
    "Chaotic ventricular electrical activity without organized QRS complexes; cardiac arrest rhythm.",
    {
      ecgCriteria: ["No identifiable QRS or T waves", "Irregular fibrillatory baseline", "No effective cardiac output"],
      diagnosticFeatures: ["Chaotic waveform", "Rate cannot be measured"],
      supportingLeads: ["II", "V1–V6"],
      differentialDiagnoses: ["Fine VF vs asystole", "Artifact"],
      recommendedNextTests: ["Immediate ACLS workup", "Serial troponin", "Coronary angiography post-ROSC"],
      recommendedManagement: ["Immediate CPR and defibrillation", "Treat reversible causes (H's and T's)"],
      icd10Code: "I49.01", snomedCode: "71908006", guidelineReferences: [AHA_ECG],
    }),
  k("AV_BLOCK_FIRST_DEGREE", "First Degree AV Block", "CONDUCTION", "MINOR", "ROUTINE",
    "Prolonged PR interval with all atrial impulses conducted to the ventricles.",
    {
      ecgCriteria: ["PR interval >200 ms", "Every P wave followed by QRS", "Regular rhythm"],
      diagnosticFeatures: ["Prolonged PR", "Otherwise normal conduction"],
      supportingLeads: ["II", "V1"],
      differentialDiagnoses: ["Enhanced vagal tone", "Medication effect"],
      recommendedNextTests: ["Medication review", "Repeat ECG if symptoms develop"],
      recommendedManagement: ["Usually no treatment required", "Monitor if progressive"],
      icd10Code: "I44.0", snomedCode: "270492004", guidelineReferences: [AHA_ECG],
    }),
  k("AV_BLOCK_SECOND_DEGREE_TYPE_I", "Second Degree AV Block Type I (Wenckebach)", "CONDUCTION", "ABNORMAL", "URGENT",
    "Progressive PR prolongation until a non-conducted P wave occurs (Mobitz type I).",
    {
      ecgCriteria: ["Grouped beating with dropped QRS", "Progressive PR lengthening before dropped beat", "Narrow QRS usually"],
      diagnosticFeatures: ["Wenckebach periodicity", "Often inferior lead context"],
      supportingLeads: ["II", "III", "aVF"],
      differentialDiagnoses: ["Mobitz II", "Non-conducted PAC"],
      recommendedNextTests: ["Continuous telemetry", "Troponin if chest pain"],
      recommendedManagement: ["Hold AV nodal blockers", "Cardiology consult if symptomatic"],
      icd10Code: "I44.1", snomedCode: "195042002", guidelineReferences: [ESC_SYNC, AHA_ECG],
    }),
  k("AV_BLOCK_SECOND_DEGREE_TYPE_II", "Second Degree AV Block Type II (Mobitz II)", "CONDUCTION", "URGENT", "EMERGENT",
    "Intermittent non-conducted P waves without progressive PR prolongation.",
    {
      ecgCriteria: ["Fixed PR in conducted beats", "Sudden dropped QRS", "Often wide QRS with bundle branch block"],
      diagnosticFeatures: ["Constant PR until blocked beat", "May progress to complete heart block"],
      supportingLeads: ["II", "V1"],
      differentialDiagnoses: ["Mobitz I", "Third-degree AV block"],
      recommendedNextTests: ["Continuous telemetry", "Echocardiography"],
      recommendedManagement: ["Urgent cardiology evaluation", "Pacemaker consideration"],
      icd10Code: "I44.1", snomedCode: "54016002", guidelineReferences: [ESC_SYNC, AHA_ECG],
    }),
  k("AV_BLOCK_COMPLETE", "Complete Heart Block", "CONDUCTION", "CRITICAL", "CRITICAL",
    "Complete dissociation of atrial and ventricular activity with independent rhythms.",
    {
      ecgCriteria: ["P waves and QRS unrelated", "Ventricular escape rhythm often slow", "Regular P-P and R-R intervals"],
      diagnosticFeatures: ["AV dissociation", "Wide escape rhythm if ventricular"],
      supportingLeads: ["II", "V1"],
      differentialDiagnoses: ["AV dissociation with VT", "Interference dissociation"],
      recommendedNextTests: ["Continuous monitoring", "Troponin", "Lyme serology if indicated"],
      recommendedManagement: ["Transcutaneous pacing if unstable", "Permanent pacemaker", "Treat reversible causes"],
      clinicalNotes: ["Ventricular escape <40 bpm is hemodynamically unstable"],
      icd10Code: "I44.2", snomedCode: "27885002", guidelineReferences: [ESC_SYNC, AHA_ECG],
    }),
  k("RBBB", "Right Bundle Branch Block", "CONDUCTION", "ABNORMAL", "ROUTINE",
    "Delayed right ventricular activation with rsR' pattern in V1 and wide S in lateral leads.",
    {
      ecgCriteria: ["QRS ≥120 ms", "rsR' or rSR' in V1", "Wide slurred S in I and V6"],
      diagnosticFeatures: ["Terminal R' in V1", "T wave inversion V1–V3 may be secondary"],
      supportingLeads: ["V1", "V6", "I"],
      differentialDiagnoses: ["Brugada pattern", "RV strain", "WPW"],
      recommendedNextTests: ["Echocardiography if new", "Chest imaging if pulmonary symptoms"],
      recommendedManagement: ["Evaluate for pulmonary or structural disease when new"],
      icd10Code: "I45.10", snomedCode: "59118001", guidelineReferences: [AHA_ECG],
    }),
  k("LBBB", "Left Bundle Branch Block", "CONDUCTION", "ABNORMAL", "URGENT",
    "Delayed left ventricular activation producing wide QRS with characteristic precordial morphology.",
    {
      ecgCriteria: ["QRS ≥120 ms", "Broad monophasic R in I, aVL, V5–V6", "Absent Q in V5–V6", "Discordant ST-T in dominant R leads"],
      diagnosticFeatures: ["Wide QRS", "Delayed intrinsicoid deflection V5–V6"],
      supportingLeads: ["V5", "V6", "I", "aVL"],
      differentialDiagnoses: ["Ventricular pacing", "WPW", "Large ventricular ectopy"],
      recommendedNextTests: ["Serial troponin if new or symptomatic", "Echocardiography"],
      recommendedManagement: ["New LBBB with ischemic symptoms = STEMI equivalent", "Evaluate for cardiomyopathy"],
      clinicalNotes: ["Complicates STEMI diagnosis when chronic"],
      icd10Code: "I44.7", snomedCode: "164947007", guidelineReferences: [AHA_STEMI, AHA_ECG],
    }),
  k("WPW", "Wolff-Parkinson-White Syndrome", "CONDUCTION", "ABNORMAL", "URGENT",
    "Ventricular pre-excitation via accessory pathway with short PR and delta wave.",
    {
      ecgCriteria: ["Short PR (<120 ms)", "Delta wave (slurred QRS upstroke)", "Wide QRS"],
      diagnosticFeatures: ["Pre-excitation pattern", "Pseudo-infarction Q waves possible"],
      supportingLeads: ["II", "V1–V6"],
      differentialDiagnoses: ["LBBB", "Hyperkalemia", "Ventricular rhythm"],
      recommendedNextTests: ["EP study for risk stratification", "Exercise testing in selected patients"],
      recommendedManagement: ["Electrophysiology referral", "Ablation curative in most cases"],
      contraindications: ["AV nodal blockers in AF with WPW", "Adenosine in wide-complex tachycardia of uncertain origin"],
      clinicalNotes: ["AF with WPW can degenerate to VF"],
      icd10Code: "I45.6", snomedCode: "74390002", guidelineReferences: [AHA_ECG, ESC_SYNC],
    }),
  k("STEMI", "ST-Elevation Myocardial Infarction", "ISCHEMIA", "CRITICAL", "CRITICAL",
    "Acute transmural myocardial infarction with ST elevation in contiguous leads requiring urgent reperfusion.",
    {
      ecgCriteria: ["ST elevation ≥1 mm in ≥2 contiguous leads (≥2 mm in V2–V3 men <40)", "New LBBB with ischemic symptoms counts as STEMI equivalent"],
      diagnosticFeatures: ["Hyperacute T waves early", "ST elevation may evolve to Q waves", "Reciprocal ST depression"],
      supportingLeads: ["Territory-dependent: V1–V4 anterior", "II, III, aVF inferior", "I, aVL, V5–V6 lateral", "V7–V9 posterior"],
      differentialDiagnoses: ["Pericarditis", "Early repolarization", "LVH strain", "Brugada", "LV aneurysm"],
      recommendedNextTests: ["Serial troponin", "Urgent coronary angiography", "Echocardiography"],
      recommendedManagement: ["Activate STEMI protocol", "Immediate reperfusion (PCI or fibrinolysis)", "Dual antiplatelet + anticoagulation"],
      clinicalNotes: ["Posterior STEMI: ST depression V1–V3 with tall R; obtain V7–V9"],
      icd10Code: "I21.3", snomedCode: "401303003", guidelineReferences: [ESC_ACS, AHA_STEMI],
    }),
  k("NSTEMI", "Non-ST-Elevation Myocardial Infarction", "ISCHEMIA", "URGENT", "EMERGENT",
    "Acute myocardial injury without persistent ST elevation, confirmed by troponin rise and ischemic ECG changes.",
    {
      ecgCriteria: ["No persistent ST elevation meeting STEMI criteria", "Ischemic ST depression or T inversion", "Elevated cardiac biomarkers"],
      diagnosticFeatures: ["ST depression", "T wave inversion", "Transient ST changes possible"],
      supportingLeads: ["Territory-dependent ST-T changes"],
      differentialDiagnoses: ["Unstable angina", "Demand ischemia", "Takotsubo", "Myocarditis"],
      recommendedNextTests: ["Serial troponin", "Echocardiography", "Coronary angiography per risk"],
      recommendedManagement: ["Antiplatelet therapy", "Anticoagulation per ACS protocol", "Early invasive strategy if high risk"],
      clinicalNotes: ["Wellens syndrome: biphasic T V2–V3 suggests critical LAD stenosis"],
      icd10Code: "I21.4", snomedCode: "401303003", guidelineReferences: [ESC_ACS, AHA_ECG],
    }),
  k("PERICARDITIS", "Pericarditis", "OTHER", "ABNORMAL", "URGENT",
    "Inflammation of the pericardium producing diffuse ST elevation and PR depression.",
    {
      ecgCriteria: ["Diffuse concave ST elevation", "PR depression", "Spodick sign (downsloping TP)", "No reciprocal ST depression except aVR/V1"],
      diagnosticFeatures: ["Four stages of ECG evolution", "No pathologic Q waves", "No loss of R waves"],
      supportingLeads: ["Diffuse limb and precordial leads", "PR depression in II, aVF, V4–V6"],
      differentialDiagnoses: ["Early repolarization", "STEMI", "Myocarditis"],
      recommendedNextTests: ["Troponin", "CRP/ESR", "Echocardiography for effusion"],
      recommendedManagement: ["NSAIDs and colchicine", "Exclude tamponade clinically"],
      contraindications: ["Anticoagulation if effusion/tamponade concern without evaluation"],
      icd10Code: "I30.9", snomedCode: "3238004", guidelineReferences: [ESC_ACS, AHA_ECG],
    }),
  k("HYPERKALEMIA", "Hyperkalemia", "ELECTROLYTE", "URGENT", "URGENT",
    "Elevated serum potassium producing progressive ECG changes from peaked T waves to sine wave pattern.",
    {
      ecgCriteria: ["Peaked T waves", "PR prolongation", "QRS widening", "Sine wave pattern in severe cases"],
      diagnosticFeatures: ["Tent-shaped T waves", "P wave flattening or absence", "Progressive QRS widening"],
      supportingLeads: ["V2–V4 for T wave morphology", "II for PR and QRS"],
      differentialDiagnoses: ["Early repolarization", "Hyperacute T waves in STEMI"],
      recommendedNextTests: ["Serum potassium STAT", "BMP", "Repeat ECG after treatment"],
      recommendedManagement: ["Calcium gluconate for membrane stabilization", "Insulin/dextrose, beta-agonists, dialysis as indicated"],
      clinicalNotes: ["ECG changes correlate poorly with absolute K+ level"],
      icd10Code: "E87.5", snomedCode: "14140009", guidelineReferences: [AHA_ECG],
    }),
  k("HYPOKALEMIA", "Hypokalemia", "ELECTROLYTE", "ABNORMAL", "URGENT",
    "Low serum potassium producing repolarization abnormalities and arrhythmia risk.",
    {
      ecgCriteria: ["T wave flattening or inversion", "Prominent U waves", "ST depression", "QT prolongation"],
      diagnosticFeatures: ["U wave best in V2–V3", "T-U fusion possible"],
      supportingLeads: ["V2", "V3", "II"],
      differentialDiagnoses: ["Digoxin effect", "Long QT syndrome"],
      recommendedNextTests: ["Serum potassium and magnesium", "Continuous monitoring during repletion"],
      recommendedManagement: ["Replace potassium cautiously", "Correct magnesium"],
      icd10Code: "E87.6", snomedCode: "43339004", guidelineReferences: [AHA_ECG],
    }),
  k("LONG_QT", "Long QT Syndrome", "CHANNELOPATHY", "URGENT", "URGENT",
    "Prolonged ventricular repolarization increasing risk of torsades de pointes.",
    {
      ecgCriteria: ["QTc >470 ms (male) or >480 ms (female)", "Prolonged repolarization"],
      diagnosticFeatures: ["Prolonged QT interval", "T wave abnormalities", "Torsades risk"],
      supportingLeads: ["II", "V5"],
      differentialDiagnoses: ["Hypocalcemia", "Drug effect", "Hypothermia", "Hypokalemia"],
      recommendedNextTests: ["Electrolytes", "Medication review", "Genetic testing if congenital suspected"],
      recommendedManagement: ["Discontinue QT-prolonging drugs", "Correct electrolytes", "Beta-blockers in congenital LQTS"],
      contraindications: ["QT-prolonging antiarrhythmics in acquired long QT"],
      icd10Code: "I45.81", snomedCode: "111975006", guidelineReferences: [AHA_ECG],
    }),
  k("SHORT_QT", "Short QT Syndrome", "CHANNELOPATHY", "ABNORMAL", "URGENT",
    "Abbreviated repolarization with tall peaked T waves and short ST segment.",
    {
      ecgCriteria: ["QTc ≤340 ms", "Tall peaked T waves", "Short ST segment"],
      diagnosticFeatures: ["Abbreviated repolarization", "Atrial fibrillation association"],
      supportingLeads: ["II", "V2–V4"],
      differentialDiagnoses: ["Hypercalcemia", "Normal variant", "Early repolarization"],
      recommendedNextTests: ["Serum calcium", "Family history", "Genetic testing"],
      recommendedManagement: ["ICD in high-risk patients", "EP specialist referral"],
      icd10Code: "I45.81", snomedCode: "764118005", guidelineReferences: [AHA_ECG],
    }),
  k("LVH", "Left Ventricular Hypertrophy", "HYPERTROPHY", "ABNORMAL", "ROUTINE",
    "Increased left ventricular mass reflected by high voltage and repolarization abnormalities.",
    {
      ecgCriteria: ["Sokolow-Lyon: S in V1 + R in V5 or V6 ≥35 mm", "Cornell criteria", "Strain pattern supports diagnosis"],
      diagnosticFeatures: ["Increased QRS voltage", "Left axis deviation", "ST-T strain in lateral leads"],
      supportingLeads: ["V1", "V5", "V6", "aVL"],
      differentialDiagnoses: ["Athletic heart", "Bundle branch block", "WPW", "Anterior MI"],
      recommendedNextTests: ["Echocardiography", "Blood pressure assessment"],
      recommendedManagement: ["Blood pressure control", "Evaluate for heart failure"],
      clinicalNotes: ["Normal ECG does not exclude LVH; echo is gold standard"],
      icd10Code: "I51.7", snomedCode: "55827005", guidelineReferences: [AHA_ECG],
    }),
  k("RVH", "Right Ventricular Hypertrophy", "HYPERTROPHY", "ABNORMAL", "URGENT",
    "Right ventricular pressure or volume overload with characteristic ECG pattern.",
    {
      ecgCriteria: ["Right axis deviation", "R > S in V1", "P pulmonale", "Supporting criteria in multiple leads"],
      diagnosticFeatures: ["Dominant R in V1", "T inversion V1–V3", "RAD >+110°"],
      supportingLeads: ["V1", "II", "aVF"],
      differentialDiagnoses: ["Posterior MI", "RBBB", "WPW", "Dextrocardia"],
      recommendedNextTests: ["Echocardiography", "Chest CT angiography if PE suspected"],
      recommendedManagement: ["Treat pulmonary hypertension cause", "Evaluate RV function"],
      clinicalNotes: ["Acute RVH suggests PE or RV infarction"],
      icd10Code: "I51.7", snomedCode: "89792004", guidelineReferences: [AHA_ECG],
    }),
  k("BRUGADA", "Brugada Syndrome", "CHANNELOPATHY", "URGENT", "URGENT",
    "Inherited sodium channelopathy with coved ST elevation in right precordial leads and sudden death risk.",
    {
      ecgCriteria: ["Type 1: coved ST elevation ≥2 mm in ≥1 of V1–V3 followed by negative T", "Spontaneous or drug-induced pattern"],
      diagnosticFeatures: ["RBBB-like pattern with ST elevation V1–V3", "Coved or saddle-back morphology"],
      supportingLeads: ["V1", "V2", "V3"],
      differentialDiagnoses: ["RBBB", "Early repolarization", "Acute MI anterior", "ARVC"],
      recommendedNextTests: ["Flecainide/ajmaline challenge if type 2/3", "Genetic testing", "Family screening"],
      recommendedManagement: ["ICD if high-risk features or prior cardiac arrest", "Avoid fever and sodium channel blockers"],
      clinicalNotes: ["Pattern may be intermittent; fever unmasks Brugada"],
      icd10Code: "I49.8", snomedCode: "233917008", guidelineReferences: [AHA_ECG],
    }),
  k("EARLY_REPOLARIZATION", "Early Repolarization", "OTHER", "NORMAL", "ROUTINE",
    "Benign J-point and ST elevation variant common in young healthy individuals.",
    {
      ecgCriteria: ["J-point elevation", "Concave ST elevation in precordial leads", "Not meeting pericarditis or STEMI criteria"],
      diagnosticFeatures: ["Terminal QRS slurring", "Stable pattern on serial ECGs", "Young age common"],
      supportingLeads: ["V2–V5", "II", "aVF"],
      differentialDiagnoses: ["Pericarditis", "STEMI", "Brugada"],
      recommendedNextTests: ["Serial ECG and troponin if chest pain", "Compare with prior tracings"],
      recommendedManagement: ["Reassurance if classic benign pattern and asymptomatic"],
      clinicalNotes: ["May overlap with inferolateral early repolarization variant; VF risk rare"],
      icd10Code: "R94.31", snomedCode: "428417006", guidelineReferences: [AHA_ECG],
    }),
];

export const ECG_CLINICAL_KNOWLEDGE_BY_ID = new Map(
  ECG_CLINICAL_KNOWLEDGE_CATALOG.map((entry) => [entry.diagnosisId, entry]),
);

export const REQUIRED_SPRINT58_DIAGNOSIS_IDS = [
  "SINUS_RHYTHM", "SINUS_BRADYCARDIA", "SINUS_TACHYCARDIA", "ATRIAL_FIBRILLATION", "ATRIAL_FLUTTER",
  "SVT", "VT", "VF", "AV_BLOCK_FIRST_DEGREE", "AV_BLOCK_SECOND_DEGREE_TYPE_I", "AV_BLOCK_SECOND_DEGREE_TYPE_II",
  "AV_BLOCK_COMPLETE", "RBBB", "LBBB", "WPW", "STEMI", "NSTEMI", "PERICARDITIS", "HYPERKALEMIA", "HYPOKALEMIA",
  "LONG_QT", "SHORT_QT", "LVH", "RVH", "BRUGADA", "EARLY_REPOLARIZATION",
] as const;
